#!/usr/bin/env node
/**
 * ibems-server authenticated proxy — architecture plan Phase 5 (auth + proxy) and Phase 6
 * (the command gate, job 3 of 3 — job 1 is `ingest.mjs`).
 *
 * The only process besides Node-RED itself allowed to reach the bridge. Validates a
 * session before forwarding anything to `127.0.0.1:1880` — this is what actually enforces
 * the "do not port-forward 1880 / LAN only" warning already written into
 * docs/bridge-contract.md and docs/phase-f-runbook.md, instead of leaving it a
 * documentation-only convention. Fronted by `tailscale serve` for TLS on the tailnet;
 * reachable in plain HTTP on the LAN, same as this Pi's other services today — the auth
 * check applies on both paths equally, since network location was never meant to be the
 * security boundary here (see the architecture plan's Phase 5 access-model decision).
 *
 * Two ways to authenticate:
 *   1. Normal — a Supabase access token, `Authorization: Bearer <token>` on HTTP,
 *      `?token=<token>` on the WS upgrade (browsers can't set custom headers on a
 *      WebSocket handshake). Verified against Supabase's own `/auth/v1/user` endpoint,
 *      with a short local cache so a live session isn't re-verified against Supabase on
 *      every single request.
 *   2. Break-glass — `POST /api/local-login {password}` against a locally-hashed password
 *      (`BREAK_GLASS_PASSWORD_HASH` in server/.env, generated by
 *      `hashBreakGlassPassword.mjs`, plaintext never stored). For on-site access when
 *      Supabase Auth itself is unreachable. Issues an opaque, server-only session token —
 *      NOT a Supabase JWT, and not accepted by anything Supabase-side. The frontend must
 *      render this distinctly ("local session — LAN only, remote access unavailable"),
 *      never as an equivalent to a normal login — see src/stores/authStore.ts. It also
 *      cannot issue device commands (see `handleCommand` below) — there is no
 *      `auth.users` row to attribute a command to, and command audit rows require one.
 *
 * `POST /api/command` (Phase 6): validates via `shared/commands.mjs` (the same pure
 * contract the mock bridge uses), writes an audit row to Supabase's `commands` table using
 * the CALLER's own verified token — not this process's anon key alone, and never the
 * service-role key `ingest.mjs` holds — so RLS's `authenticated` policy is what actually
 * grants the insert, and `requested_by` is the real signed-in user. Dispatch itself stays
 * gated behind `HARDWARE_DISPATCH_ENABLED` (default unset/false): the ack is always
 * honest about what happened (`status: 'dry_run'` while closed).
 *
 * Phase 7 (lights only): with the gate open, a `switch`-class command is forwarded for
 * real to the live Node-RED flow's `POST /light/:id` (see `dispatchLight.mjs`) — the
 * same entry point the physical node-red-dashboard UI already uses. Outlets and the ACU
 * have no equivalent endpoint and stay `dry_run` even with the gate open; building those
 * is separate, later work. `GET /api/capabilities` reports that asymmetry as
 * `dispatch_classes` so the UI can name which controls are actually live, rather than
 * treating an open gate as "everything on this page now moves hardware."
 */

import http from 'node:http';
import net from 'node:net';
import crypto from 'node:crypto';
import { URL, fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { verifyBreakGlassPassword } from './breakGlass.mjs';
import { validateCommand, buildAck, ACCEPTED_STATUS } from '../shared/commands.mjs';
import { DEVICE_REGISTRY, TIMING, SITE } from '../shared/registry.mjs';
import { dispatchCommand, DISPATCH_CLASSES } from './dispatchLight.mjs';
import { createTuyaClient, TUYA_HOSTS } from './tuyaCloud.mjs';
import { toPublicFleet } from './tuyaFleet.mjs';
import { joinMacPresence, readNeighbours, toPublicPresence } from './macPresence.mjs';
import { createAdminClient } from '../node-red-bridge/nodeRedAdmin.mjs';
import { auditedDispatch } from './auditedDispatch.mjs';
import { createJwksCache } from './jwksCache.mjs';
import { verifyEs256Jwt } from './jwtVerify.mjs';
import { createBufferedAudit } from './auditQueue.mjs';
import { bufferCount } from './ingestBuffer.mjs';
import { buildCloudDispatch } from './cloudDispatchConfig.mjs';
import { handleEnroll } from './enrollRoute.mjs';
import { handleRemove } from './removeRoute.mjs';

/**
 * The Tuya cloud client, or null when the credentials are absent. Built lazily so the proxy
 * still starts without them — the cloud view is an addition, and a deployment that has not
 * been given Tuya credentials should lose that one endpoint, not fail to boot.
 *
 * TUYA_ACCESS_SECRET never leaves this process. `/api/tuya/devices` returns an allowlisted
 * shape (see tuyaFleet.mjs); the browser bundle carries the Supabase anon key and nothing else.
 */
let tuyaClient;
function getTuyaClient() {
  if (tuyaClient !== undefined) return tuyaClient;
  const accessId = process.env.TUYA_ACCESS_ID;
  const accessSecret = process.env.TUYA_ACCESS_SECRET;
  const host = TUYA_HOSTS[(process.env.TUYA_REGION ?? '').toLowerCase()];
  tuyaClient = accessId && accessSecret && host ? createTuyaClient({ accessId, accessSecret, host }) : null;
  return tuyaClient;
}

/**
 * The vendor-cloud fallback, or null when it is not configured — which is the ordinary case
 * and not an error. Built once at startup: constructing a client per command would re-read the
 * flow file and re-authenticate on a path that only runs when something is already wrong.
 */
const CLOUD_DISPATCH = buildCloudDispatch(process.env);

/**
 * The bridge own view of whether a device is reachable, used to stop a local dispatch claiming
 * success it cannot have had. Returns `true`/`false`, or `null` when the bridge could not be
 * asked — see `dispatchCommand`, which treats `null` as "attempt local anyway" on purpose.
 *
 * Deliberately unmemoised. This is read on a user-initiated command, not in a loop, and the
 * whole point is that it is current: a cached "online" from thirty seconds ago is the same
 * fabrication the HTTP 2xx was.
 */
async function readDeviceOnline(device) {
  try {
    const res = await fetch(`http://${BRIDGE_HOST}:${BRIDGE_PORT}/api/readings/latest`, {
      signal: AbortSignal.timeout(5000),
    });
    if (!res.ok) return null;
    const rows = await res.json();
    const row = Array.isArray(rows) ? rows.find((r) => r.device_id === device.id) : null;
    return row ? row.online === true : null;
  } catch {
    return null;
  }
}

const PROXY_PORT = Number(process.env.PROXY_PORT) || 8080;
const BRIDGE_HOST = process.env.BRIDGE_HOST || '127.0.0.1';
const BRIDGE_PORT = Number(process.env.BRIDGE_PORT) || 1880;
// How long to wait on an upstream that has accepted the connection but not answered.
// Overridable only so the test suite can exercise the hang path without waiting 10s for it;
// the default is the same budget every other bridge call in this repo uses.
const BRIDGE_TIMEOUT_MS = Number(process.env.BRIDGE_TIMEOUT_MS) || TIMING.FETCH_TIMEOUT_MS;
const SUPABASE_URL = process.env.SUPABASE_URL;
// The ANON key, not service-role — verifying a user's own token needs no elevated
// privilege, and this process's whole point is to hold less power than ingest.mjs, not more.
const SUPABASE_ANON_KEY = process.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY;
const BREAK_GLASS_PASSWORD_HASH = process.env.BREAK_GLASS_PASSWORD_HASH;
const SUPABASE_VERIFY_CACHE_MS = 60_000;

/**
 * OFFLINE OPERATION. The Tuya fleet is local — the devices sit on the Pi's own segment and
 * answer local keys — so commanding them needs no internet whatsoever. Two things did need it
 * anyway, and between them they reduced the offline command window to zero: this file verified
 * every session by calling Supabase, and `auditedDispatch` wrote the audit row there before
 * dispatching. A WAN outage therefore removed control of the whole building while the device
 * layer sat there working.
 *
 * Neither safety property is being relaxed. Sessions are still verified and commands are still
 * recorded before a relay moves; both simply gain an implementation that does not require a
 * link to the internet. See jwtVerify.mjs and auditQueue.mjs for the limits of each.
 */
const JWKS_URL = SUPABASE_URL ? `${SUPABASE_URL}/auth/v1/.well-known/jwks.json` : null;
const JWKS_ISSUER = SUPABASE_URL ? `${SUPABASE_URL}/auth/v1` : null;
const JWKS_CACHE_PATH = process.env.JWKS_CACHE_PATH || join(dirname(fileURLToPath(import.meta.url)), 'data', 'jwks.json');
const JWKS_REFRESH_MS = 6 * 60 * 60 * 1000; // 6h — signing keys rotate rarely
const COMMAND_BUFFER_PATH = process.env.COMMAND_AUDIT_BUFFER_PATH || join(dirname(fileURLToPath(import.meta.url)), 'data', 'command-audit-buffer.ndjson');
/**
 * The scheduler records to its own file (one writer per file — see auditQueue.mjs), but the
 * backlog reported to the UI has to cover both. "The audit trail is behind" is one fact about
 * the system, and a scheduled command waiting to upload is exactly as behind as a manual one.
 */
const SCHEDULER_BUFFER_PATH = process.env.SCHEDULER_AUDIT_BUFFER_PATH || join(dirname(fileURLToPath(import.meta.url)), 'data', 'command-audit-buffer-scheduler.ndjson');

const jwks = JWKS_URL ? createJwksCache({ url: JWKS_URL, cachePath: JWKS_CACHE_PATH }) : null;

const LOCAL_SESSION_TTL_MS = 12 * 60 * 60 * 1000; // 12h
// Closed by default, mirroring node-red-bridge/deploy.mjs's --apply-only-with-explicit-
// intent pattern. Phase 7 is the only phase allowed to flip this in a real deployment.
const HARDWARE_DISPATCH_ENABLED = process.env.HARDWARE_DISPATCH_ENABLED === 'true';
// Shared secret with the live Node-RED flow's "Auth + validate" function (POST
// /light/:id) — see dispatchLightCommand below. Only ever needed when the gate above is
// open; local/mock-bridge dev never sets HARDWARE_DISPATCH_ENABLED, so this stays unset there.
const LIGHT_API_TOKEN = process.env.LIGHT_API_TOKEN || null;



if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('[ibems-proxy] SUPABASE_URL and VITE_SUPABASE_ANON_KEY are required — see server/.env.example');
  process.exit(1);
}
if (!BREAK_GLASS_PASSWORD_HASH) {
  console.warn('[ibems-proxy] BREAK_GLASS_PASSWORD_HASH not set — /api/local-login will 501 until it is (see server/hashBreakGlassPassword.mjs)');
}
// Hard fail-fast, not a warn-and-degrade like BREAK_GLASS_PASSWORD_HASH above: a proxy
// that believes it can dispatch to real hardware but has no way to authenticate to the
// light endpoint is a dangerous half-configuration, not a safe degraded mode.
if (HARDWARE_DISPATCH_ENABLED && !LIGHT_API_TOKEN) {
  console.error(
    '[ibems-proxy] HARDWARE_DISPATCH_ENABLED=true but LIGHT_API_TOKEN is unset — refusing to start. ' +
      'A hardware-dispatch-capable proxy with no way to authenticate to the light endpoint is a dangerous ' +
      'half-configuration, not a safe degraded mode. Set LIGHT_API_TOKEN in server/.env, or leave HARDWARE_DISPATCH_ENABLED unset/false.',
  );
  process.exit(1);
}

// --- local (break-glass) sessions: opaque token -> expiry, in-memory only. Restarting
// this process invalidates every local session — acceptable for a rare, on-site fallback. ---
const localSessions = new Map();

function issueLocalSession() {
  const token = crypto.randomBytes(32).toString('hex');
  localSessions.set(token, Date.now() + LOCAL_SESSION_TTL_MS);
  return token;
}
function isValidLocalSession(token) {
  const exp = localSessions.get(token);
  if (!exp) return false;
  if (Date.now() > exp) {
    localSessions.delete(token);
    return false;
  }
  return true;
}
setInterval(() => {
  const now = Date.now();
  for (const [t, exp] of localSessions) if (now > exp) localSessions.delete(t);
}, 60_000).unref();

// --- Supabase token verification, cached briefly to avoid a round trip per request ------
const supabaseVerifyCache = new Map(); // token -> { validUntil, ok, userId }

// Entries were never evicted. Supabase mints a NEW access token on every refresh, and
// src/lib/authToken.ts refreshes on every 401, so this accumulated one entry per token ever
// presented for the life of the process — only `validUntil` went stale, never the entry.
// Slow, uncapped, and bounded by nothing an operator controls. localSessions has had a
// sweep since Phase 5; this is the same sweep, plus a hard ceiling so a burst of distinct
// tokens between sweeps cannot grow it without limit either.
const SUPABASE_VERIFY_CACHE_MAX = 5000;
setInterval(() => {
  const now = Date.now();
  for (const [t, entry] of supabaseVerifyCache) if (now >= entry.validUntil) supabaseVerifyCache.delete(t);
}, 60_000).unref();

/** Map preserves insertion order, so deleting from the front evicts the oldest entries. */
function capVerifyCache() {
  while (supabaseVerifyCache.size > SUPABASE_VERIFY_CACHE_MAX) {
    supabaseVerifyCache.delete(supabaseVerifyCache.keys().next().value);
  }
}

/** Returns `{ok, userId}` — `userId` is `auth.users.id`, needed by `handleCommand` to
 * attribute a command's audit row to a real user. Kept in the same cache entry as `ok`
 * rather than a second lookup, so a cached miss and a cached user id can never disagree. */
async function verifySupabaseSession(token) {
  const cached = supabaseVerifyCache.get(token);
  if (cached && Date.now() < cached.validUntil) return cached;
  let result = { ok: false, userId: null };
  try {
    const res = await fetch(`${SUPABASE_URL}/auth/v1/user`, {
      headers: { Authorization: `Bearer ${token}`, apikey: SUPABASE_ANON_KEY },
      signal: AbortSignal.timeout(5000),
    });
    if (res.ok) {
      const body = await res.json();
      result = { ok: true, userId: typeof body?.id === 'string' ? body.id : null };
    }
  } catch {
    // Supabase unreachable — NOT the same fact as "invalid token", and the difference is now
    // load-bearing rather than merely noted.
    //
    // NETWORK-FIRST, DELIBERATELY. The call above is authoritative and is the ONLY check that
    // notices a session the user has since signed out of; local verification cannot see a
    // revocation. So it stays the primary path and its answer is never second-guessed — a 401
    // from Supabase lands in the `res.ok` branch above and is a refusal, not an outage.
    //
    // Only when the question could not be ASKED does the offline path apply: verify the
    // token's ES256 signature against the cached JWKS. Strictly weaker, and used only when the
    // alternative is losing control of a building full of devices that are all still reachable.
    const local = jwks ? verifyEs256Jwt(token, jwks.keys(), { issuer: JWKS_ISSUER }) : { ok: false, reason: 'no jwks configured' };
    if (local.ok) {
      // Not cached: the cache exists to spare Supabase repeat questions, and this answer was
      // reached without asking it. Caching would also outlive the outage and keep a stale
      // verdict alive after the authoritative check became available again.
      return { ok: true, userId: local.userId, offline: true };
    }
    console.error(`[ibems-proxy] Supabase unreachable and offline verification failed: ${local.reason}`);
    result = { ok: false, userId: null };
  }
  supabaseVerifyCache.set(token, { ...result, validUntil: Date.now() + SUPABASE_VERIFY_CACHE_MS });
  capVerifyCache();
  return result;
}

async function isAuthorized(token) {
  if (!token) return false;
  if (isValidLocalSession(token)) return true;
  return (await verifySupabaseSession(token)).ok;
}

function tokenFromRequest(req, url) {
  const header = req.headers['authorization'];
  if (header?.startsWith('Bearer ')) return header.slice(7);
  return url.searchParams.get('token') || null;
}

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'content-type, authorization',
  'Access-Control-Max-Age': '600',
};

function sendJson(res, status, body) {
  res.writeHead(status, { 'Content-Type': 'application/json', ...CORS_HEADERS });
  res.end(JSON.stringify(body));
}

async function readJsonBody(req) {
  let raw = '';
  for await (const chunk of req) raw += chunk;
  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

async function handleLocalLogin(req, res) {
  if (!BREAK_GLASS_PASSWORD_HASH) return sendJson(res, 501, { error: 'break_glass_not_configured' });
  const body = await readJsonBody(req);
  const password = body?.password;
  if (!verifyBreakGlassPassword(password, BREAK_GLASS_PASSWORD_HASH)) {
    return sendJson(res, 401, { error: 'invalid_password' });
  }
  const token = issueLocalSession();
  sendJson(res, 200, { token, expires_in: LOCAL_SESSION_TTL_MS / 1000, mode: 'local' });
}

/** Forwards to the real bridge, stripping the proxy-only `token` query param first — the
 * bridge has no concept of it, and for GET history requests the *other* query params
 * (device_id, range) still need to pass through untouched. */
function proxyHttp(req, res, url) {
  const upstream = new URL(url);
  upstream.searchParams.delete('token');

  const proxyReq = http.request(
    { hostname: BRIDGE_HOST, port: BRIDGE_PORT, path: upstream.pathname + upstream.search, method: req.method, headers: { ...req.headers, host: `${BRIDGE_HOST}:${BRIDGE_PORT}` } },
    (proxyRes) => {
      // Node-RED's httpNodeCors already sends its own `access-control-*` headers (all
      // lowercase — Node always normalizes incoming header names). Spreading those
      // alongside our own CORS_HEADERS (capitalized keys) used to produce a response with
      // the SAME header twice under different casing — e.g. two Access-Control-Allow-Origin
      // values. That's invalid per the Fetch/CORS spec, and a browser rejects the response
      // outright with a fast, silent "Failed to fetch" — no server-side error, no slow
      // network involved. curl doesn't enforce CORS at all, so every curl-based check
      // during this bug's investigation looked fine; only a real browser could ever have
      // shown it. Strip the upstream's CORS headers before applying ours so exactly one
      // version of each survives.
      const headers = { ...proxyRes.headers };
      for (const key of Object.keys(headers)) {
        if (key.toLowerCase().startsWith('access-control-')) delete headers[key];
      }
      res.writeHead(proxyRes.statusCode, { ...headers, ...CORS_HEADERS });
      proxyRes.pipe(res);
    }
  );
  // A bridge that REFUSES a connection raises 'error' and is handled below. A bridge that
  // ACCEPTS and then hangs raises nothing at all, and without this timeout the request would
  // sit open indefinitely, holding a socket on both legs. Node-RED under a Tuya
  // discovery-retry storm is exactly the process that hangs rather than refuses — the
  // condition that produced ~104,500 journal lines an hour and needed
  // server/nodered-log-ratelimit.conf. The client's own abort would free the browser side,
  // but never this one.
  proxyReq.setTimeout(BRIDGE_TIMEOUT_MS, () => {
    proxyReq.destroy(new Error(`bridge did not respond within ${BRIDGE_TIMEOUT_MS}ms`));
  });

  proxyReq.on('error', (err) => {
    // The upstream detail goes to the journal, not to the caller. `String(err)` on a
    // Supabase or bridge error can carry project-identifying strings, and the caller has no
    // use for them — dispatchLight.mjs's 502 path already draws this line; the two
    // bridge-facing paths here did not.
    console.error(`[ibems-proxy] upstream ${req.method} ${upstream.pathname} failed: ${String(err)}`);
    // A hang that trips the timeout above may already have had headers written if the
    // bridge started responding and then stalled mid-body; there is no second status line
    // to send in that case, only a socket to close.
    if (res.headersSent) return res.destroy();
    sendJson(res, 502, { error: 'bridge_unreachable', detail: 'The Node-RED bridge did not respond.' });
  });
  req.pipe(proxyReq);
}

/**
 * `POST /api/command` — architecture plan Phase 6. `token` has already passed the generic
 * `isAuthorized` gate (so it's either a valid break-glass session or a valid Supabase
 * token) by the time this is called; this function applies the STRICTER rule commands
 * need on top of that.
 */
async function handleCommand(req, res, token) {
  const session = await verifySupabaseSession(token);
  if (!session.ok || !session.userId) {
    // isAuthorized() already accepted this token, so if it's not a real Supabase session
    // it must be a valid break-glass one — reject with a reason the frontend can render
    // distinctly from "not logged in at all" (401).
    return sendJson(res, 403, {
      error: 'break_glass_cannot_command',
      detail: 'Local/break-glass sessions are view-only — device commands require a real Supabase-authenticated session.',
    });
  }

  const body = await readJsonBody(req);
  // SITE.policy carries this building's own bounds — e.g. the minimum aircon setpoint the
  // operator permits, which is narrower than what the IR library can physically send.
  const validated = validateCommand(body, DEVICE_REGISTRY, SITE.policy);
  if (!validated.ok) {
    return sendJson(res, validated.status, { error: validated.error, code: validated.code });
  }

  const { cmd } = validated;
  const device = DEVICE_REGISTRY.find((d) => d.id === cmd.device_id); // already validated to exist
  const acceptedAtMs = Date.now();
  const ack = buildAck(cmd, acceptedAtMs);

  // The audit row is written with the CALLER's own token, not SUPABASE_ANON_KEY alone —
  // RLS's `auth.role() = 'authenticated'` check needs the request to actually carry a
  // signed-in user's session for PostgREST to grant the insert.
  const sbCommands = (path, init) =>
    fetch(`${SUPABASE_URL}/rest/v1/commands${path}`, {
      ...init,
      headers: { Authorization: `Bearer ${token}`, apikey: SUPABASE_ANON_KEY, 'Content-Type': 'application/json', ...init.headers },
      signal: AbortSignal.timeout(5000),
    });

  // Which classes really reach hardware is declared once, in dispatchLight.mjs, next to the
  // routing that implements it — so what /api/capabilities advertises and what this function
  // will actually do cannot drift apart. The record-then-act ordering is shared with
  // scheduler.mjs via auditedDispatch, so the two paths cannot disagree about what a failed
  // audit insert means (they used to: this one refused, the scheduler carried on).
  // The record-then-act contract is untouched: auditedDispatch still refuses to dispatch
  // unless the command was recorded first. `createBufferedAudit` only changes where
  // "recorded" is allowed to land when Supabase cannot be reached at all.
  const remoteAudit = {
    insert: async (row) => {
      try {
        const res = await sbCommands('', { method: 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify(row) });
        // A status code is Supabase ANSWERING. A 4xx means this caller may not write that row,
        // which is a refusal and must stay one — see auditQueue.mjs on why laundering it into
        // a local queue entry would be the dangerous mistake.
        if (!res.ok) return { ok: false, detail: `HTTP ${res.status} ${await res.text().catch(() => '')}` };
        const body = await res.json().catch(() => null);
        return { ok: true, id: Array.isArray(body) ? body[0]?.id : body?.id };
      } catch (err) {
        // A throw is the transport failing: no answer was obtained. Only this may be buffered.
        return { ok: false, unreachable: true, detail: String(err) };
      }
    },
    update: async (id, patch) => {
      try {
        // `return=representation`, not `return=minimal`, so the affected-row count can be
        // checked. PostgREST reports an RLS-blocked UPDATE as a success with an empty
        // result — the exact trap 2e4c0c2 fixed on the schedule-save path, where a write
        // that changed nothing reported "saved". An empty array here means the row was not
        // updated, whatever the status code says.
        const res = await sbCommands(`?id=eq.${encodeURIComponent(id)}`, { method: 'PATCH', headers: { Prefer: 'return=representation' }, body: JSON.stringify(patch) });
        if (!res.ok) return { ok: false, detail: `HTTP ${res.status} ${await res.text().catch(() => '')}` };
        const rows = await res.json().catch(() => null);
        if (!Array.isArray(rows) || rows.length === 0) {
          return { ok: false, detail: 'update affected no rows — check supabase/phase9_command_outcome.sql is applied' };
        }
        return { ok: true };
      } catch (err) {
        return { ok: false, unreachable: true, detail: String(err) };
      }
    },
  };

  // The record-then-act contract is untouched: auditedDispatch still refuses to dispatch
  // unless the command was recorded first. This only changes where "recorded" is allowed to
  // land when Supabase cannot be reached at all.
  const audit = createBufferedAudit({
    bufferPath: COMMAND_BUFFER_PATH,
    insert: remoteAudit.insert,
    update: remoteAudit.update,
  });

  const outcome = await auditedDispatch({
    device,
    cmd,
    note: ack.note,
    auditRow: {
      command_id: cmd.command_id ?? null,
      device_id: cmd.device_id,
      socket: cmd.socket ?? null,
      action: cmd.action,
      target: cmd.target,
      requested_by: session.userId,
      accepted_at: new Date(acceptedAtMs).toISOString(),
      confirmed: false,
      confirmation: 'none',
      source: 'ibems-app',
    },
    dispatchEnabled: HARDWARE_DISPATCH_ENABLED,
    dispatchClasses: DISPATCH_CLASSES,
    dispatch: (d, c) => dispatchCommand(d, c, {
      bridgeHost: BRIDGE_HOST,
      bridgePort: BRIDGE_PORT,
      lightApiToken: LIGHT_API_TOKEN,
      cloud: CLOUD_DISPATCH,
      readOnline: readDeviceOnline,
    }),
    insertAudit: audit.insertAudit,
    updateAudit: audit.updateAudit,
    log: (msg) => console.error(`[ibems-proxy] ${msg}`),
  });

  // Audit completeness is part of Phase 6's DoD: no row, no command. With record-first this
  // is now a genuine refusal rather than a report of one — nothing has touched hardware.
  if (outcome.auditFailure) {
    console.error(`[ibems-proxy] command audit insert failed: ${outcome.auditFailure}`);
    return sendJson(res, 502, { error: 'audit_log_unreachable', detail: 'Could not record this command — refusing to proceed without an audit trail.' });
  }

  // The attempt is logged above (status:'failed', not silently omitted — an
  // attempted-and-failed command is exactly what a safety-critical audit trail exists to
  // capture) before this refusal, so the record survives even though the caller gets an
  // error rather than the ack.
  if (outcome.dispatchFailure) {
    // One code per failure MODE, not one code for "dispatch failed".
    //
    // Every one of these used to answer `hardware_dispatch_failed`, which the app rendered as
    // "The bridge did not accept the command (502)." So "the bridge reports THIS DEVICE
    // offline" — a fact about one socket, with a remedy at that socket — was indistinguishable
    // from the bridge being down. A physical test on 2026-08-31 reported exactly that
    // misreading as "bridge not reachable", while the bridge was serving readings throughout,
    // and it sent the diagnosis in the wrong direction for a fortnight.
    //
    // `detail` stays generic and names no host, port or upstream body: this response crosses
    // into a browser. The specifics are in the audit row and the journal.
    const FAILURE = {
      device_offline: {
        code: 'device_offline',
        detail: 'The bridge has no connection to this device, so the command could not reach it. The command was logged.',
      },
      bridge_unreachable: {
        code: 'bridge_unreachable',
        detail: 'The bridge could not be reached, so the command was not delivered. The command was logged.',
      },
      bridge_rejected: {
        code: 'bridge_rejected',
        detail: 'The bridge refused the command. The command was logged.',
      },
      no_route: {
        code: 'no_dispatch_route',
        detail: 'This deployment has no way to command a device of this kind. The command was logged.',
      },
    };
    const mapped = FAILURE[outcome.dispatchReason] ?? {
      code: 'hardware_dispatch_failed',
      detail: 'The command was validated and logged, but the device did not actually respond — refusing to report it as accepted.',
    };
    return sendJson(res, 502, {
      error: mapped.code,
      code: mapped.code,
      detail: mapped.detail,
      // Which paths were tried. `none` means local AND the vendor cloud both failed, which is a
      // different situation from a deployment with no cloud configured at all — and the two
      // read identically without this.
      via: outcome.via ?? null,
    });
  }

  res.writeHead(ACCEPTED_STATUS, { 'Content-Type': 'application/json', ...CORS_HEADERS });
  // `via` rides on the ack so the page can say HOW the command landed. A cloud-recovered
  // command is a success the operator would otherwise read as unremarkable, while it means the
  // device stopped answering locally — the earliest warning this system has that a device is
  // going bad. Null for a dry run, where no path was attempted.
  res.end(JSON.stringify({ ...ack, via: outcome.via ?? null }));
}

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  const origin = req.headers['origin'] || '-';

  if (req.method === 'OPTIONS') {
    console.log(`[ibems-proxy] OPTIONS ${url.pathname} origin=${origin}`);
    res.writeHead(204, CORS_HEADERS);
    return res.end();
  }
  if (req.method === 'POST' && url.pathname === '/api/local-login') {
    console.log(`[ibems-proxy] POST /api/local-login origin=${origin}`);
    return handleLocalLogin(req, res);
  }

  const token = tokenFromRequest(req, url);
  const authorized = await isAuthorized(token);
  console.log(`[ibems-proxy] ${req.method} ${url.pathname} origin=${origin} token=${token ? token.slice(0, 12) + '…' : 'none'} -> ${authorized ? 'OK' : '401'}`);
  if (!authorized) return sendJson(res, 401, { error: 'unauthorized' });

  if (req.method === 'GET' && url.pathname === '/api/tuya/devices') {
    const client = getTuyaClient();
    // 501, not 500: the deployment has not been given Tuya credentials, which is a
    // configuration state rather than a fault. The frontend hides the column instead of
    // showing an error for something nobody asked for.
    if (!client) return sendJson(res, 501, { error: 'tuya_not_configured' });
    try {
      const devices = await client.listDevices();
      // Which vendor devices already have a node. Read fresh rather than cached at startup:
      // enrolling one changes this, and a wizard showing a device it just added as still
      // available is worse than one extra read on a page nobody opens often.
      let claimed = new Set();
      let claimedKnown = false;
      try {
        const auth = await createAdminClient({ host: '127.0.0.1', port: BRIDGE_PORT, timeoutMs: 10000 });
        const { flows } = await auth.getFlows(await auth.login());
        claimed = new Set(flows.filter((n) => n.type === 'tuya-smart-device').map((n) => n.deviceId));
        claimedKnown = true;
      } catch (err) {
        // Reported, not swallowed. This read needs NODE_RED_ADMIN_USER/PASS, which the Tuya
        // call does not — so it fails independently, and on failure every `claimed` is false,
        // which is indistinguishable from an empty flow. The wizard then offers devices that
        // already have a node as available: a wrong list that looks right. That is exactly
        // what happened when these keys were missing from server/.env, and it stayed invisible
        // because this catch was empty. `claimed_known` lets the page say it does not know.
        console.error(`[ibems-proxy] claimed-set lookup failed, enrolment candidates unfiltered: ${err.message}`);
      }
      return sendJson(res, 200, { devices: toPublicFleet(devices, claimed), claimed_known: claimedKnown });
    } catch (err) {
      // The upstream message can name the data centre and the account; log it, do not echo it.
      console.error(`[ibems-proxy] tuya fleet fetch failed: ${err.message}`);
      return sendJson(res, 502, { error: 'tuya_unavailable' });
    }
  }
  if (req.method === 'GET' && url.pathname === '/api/tuya/presence') {
    // FI-015. Joins the cloud's per-device MAC against this host's ARP table, which is the one
    // diagnostic that separates "off the network, someone must drive to the office" from "on
    // the network but no longer discoverable, which is a config change". It existed only as
    // `npm run tuya:macs` — correct, but reachable solely over SSH, and the split it reports
    // moved twice inside an hour on 2026-08-26. A perishable answer that decides whether
    // somebody makes a journey should not require a terminal.
    const client = getTuyaClient();
    if (!client) return sendJson(res, 501, { error: 'tuya_not_configured' });
    try {
      const devices = await client.listDevices();
      const factoryInfos = await client.listFactoryInfos(devices.map((d) => d.id));
      // Unlike /api/tuya/devices this reads the HOST's neighbour table, so it means nothing
      // anywhere but the Pi. `readable` carries that: an empty table would otherwise be joined
      // into "every device is absent", which is the strongest claim available made from the
      // weakest evidence, and on screen would read as the whole fleet having left the network.
      const { readable, neighbours, reason } = readNeighbours();
      if (!readable) console.warn(`[ibems-proxy] /api/tuya/presence has no ARP view: ${reason}`);
      const rows = joinMacPresence({ cloudDevices: devices, factoryInfos, neighbours });
      return sendJson(res, 200, {
        arp_readable: readable,
        devices: toPublicPresence(rows, { arpReadable: readable }),
      });
    } catch (err) {
      // The upstream message can name the data centre and the account; log it, do not echo it.
      console.error(`[ibems-proxy] tuya presence fetch failed: ${err.message}`);
      return sendJson(res, 502, { error: 'tuya_unavailable' });
    }
  }
  if (req.method === 'GET' && url.pathname === '/api/capabilities') {
    // dispatch_classes is what the gate means in practice, not just whether it is open:
    // with the gate closed nothing dispatches, so the list is empty. The frontend uses it to
    // say which controls are live rather than going silent the moment the gate opens.
    // How many commands were recorded locally because Supabase could not be reached. A
    // command accepted into the buffer is not the same fact as one recorded in the audit
    // table, and the operator must not have to guess which they just did — this project's
    // whole posture is that the UI never claims more than it can observe.
    return sendJson(res, 200, {
      hardware_dispatch_enabled: HARDWARE_DISPATCH_ENABLED,
      dispatch_classes: HARDWARE_DISPATCH_ENABLED ? DISPATCH_CLASSES : [],
      audit_buffer_pending: bufferCount(COMMAND_BUFFER_PATH) + bufferCount(SCHEDULER_BUFFER_PATH),
    });
  }
  if (req.method === 'POST' && url.pathname === '/api/enroll') {
    // Authenticated like every other route above. Deliberately NOT behind
    // HARDWARE_DISPATCH_ENABLED: that gate governs moving a relay, and enrolling a device
    // moves nothing. Conflating the two would mean a site that has not opened dispatch could
    // never add a device, which is backwards — you enrol before you switch.
    return handleEnroll(req, res, { readJsonBody, sendJson, token });
  }
  if (req.method === 'POST' && url.pathname === '/api/remove') {
    // Same gate reasoning as enrolment, and the same authentication. Unlike enrolment this
    // needs no vendor cloud — removal reads the flow and the registry only, so it stays
    // available on a deployment with no Tuya credentials, which is also the deployment most
    // likely to need to undo something.
    return handleRemove(req, res, { readJsonBody, sendJson, token });
  }
  if (req.method === 'POST' && url.pathname === '/api/command') {
    return handleCommand(req, res, token);
  }

  proxyHttp(req, res, url);
});

// WebSocket relay: raw TCP, not a WS library — we never parse frames, just authenticate
// the handshake then pipe bytes both directions. Node-RED does the actual WS protocol
// work on the other end; this process only ever forwards.
server.on('upgrade', async (req, clientSocket, head) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  const token = tokenFromRequest(req, url);
  const authorized = await isAuthorized(token);
  console.log(`[ibems-proxy] WS upgrade ${url.pathname} origin=${req.headers['origin'] || '-'} token=${token ? token.slice(0, 12) + '…' : 'none'} -> ${authorized ? 'OK' : '401'}`);
  if (!authorized) {
    clientSocket.write('HTTP/1.1 401 Unauthorized\r\n\r\n');
    clientSocket.destroy();
    return;
  }

  const bridgeSocket = net.connect(BRIDGE_PORT, BRIDGE_HOST, () => {
    const upstream = new URL(url);
    upstream.searchParams.delete('token');
    const lines = [`GET ${upstream.pathname}${upstream.search} HTTP/1.1`];
    for (const [key, value] of Object.entries(req.headers)) {
      if (key.toLowerCase() === 'host') continue;
      lines.push(`${key}: ${value}`);
    }
    lines.push(`Host: ${BRIDGE_HOST}:${BRIDGE_PORT}`, '', '');
    bridgeSocket.write(lines.join('\r\n'));
    if (head?.length) bridgeSocket.write(head);
    bridgeSocket.pipe(clientSocket);
    clientSocket.pipe(bridgeSocket);
  });
  bridgeSocket.on('error', () => clientSocket.destroy());
  clientSocket.on('error', () => bridgeSocket.destroy());
});

server.listen(PROXY_PORT, () => {
  console.log(`[ibems-proxy] listening on :${PROXY_PORT}, forwarding authorized requests to ${BRIDGE_HOST}:${BRIDGE_PORT}`);
});

/**
 * Keep the offline verification keys current. Best-effort by design: a failure here is
 * ordinary (it is exactly what an outage looks like) and must never stop the proxy serving.
 * The keys already on disk stay valid, which is the entire point of persisting them.
 */
if (jwks) {
  const refreshJwks = async () => {
    const res = await jwks.refresh();
    if (res.ok) console.log(`[ibems-proxy] offline session keys refreshed (${res.count})`);
    else console.warn(`[ibems-proxy] could not refresh offline session keys (${res.detail}); using ${res.count} cached`);
  };
  refreshJwks();
  // unref: this timer must not hold the process open at shutdown.
  setInterval(refreshJwks, JWKS_REFRESH_MS).unref();
}

for (const sig of ['SIGTERM', 'SIGINT']) {
  process.on(sig, () => {
    console.log(`[ibems-proxy] received ${sig}, shutting down`);
    // server.close() alone stops accepting NEW connections but waits indefinitely for
    // existing ones to end on their own — a live WS relay (see the 'upgrade' handler
    // above) never closes by itself, so a browser with the dashboard open would leave
    // this hanging until systemd's stop timeout expired and SIGKILLed it (~90s of the
    // proxy being unreachable on every single restart — confirmed the hard way, see the
    // architecture plan's Phase 5 incident notes). closeAllConnections() forcibly ends
    // every socket the http.Server itself tracks, but measured ~27s to actually exit
    // with a real WS held open — an upgraded connection's *relayed* outbound leg (the
    // separate `net.connect()` to the bridge in the 'upgrade' handler) isn't one of
    // those tracked sockets, so something was still lingering. A hard timeout below
    // guarantees a prompt exit regardless of what closeAllConnections() does or doesn't
    // reach — don't trust the graceful path alone a second time without re-verifying.
    server.close(() => process.exit(0));
    server.closeAllConnections();
    setTimeout(() => process.exit(0), 2000);
  });
}
