#!/usr/bin/env node
/**
 * ibems-server authenticated proxy — architecture plan Phase 5 (auth + proxy) and Phase 6
 * (the command gate, job 3 of 3 — job 1 is `ingest.mjs`).
 *
 * The only process besides Node-RED itself allowed to reach the bridge. Validates a
 * session before forwarding anything to `127.0.0.1:1880` — this is what actually enforces
 * the "do not port-forward 1880 / LAN only" warning already written into
 * docs/bridge-contract.md and docs/phase-f-runbook.md, instead of leaving it a
 * documentation-only convention. Fronted by `tailscale serve` for TLS on the tailnet;
 * reachable in plain HTTP on the LAN, same as this Pi's other services today — the auth
 * check applies on both paths equally, since network location was never meant to be the
 * security boundary here (see the architecture plan's Phase 5 access-model decision).
 *
 * Two ways to authenticate:
 *   1. Normal — a Supabase access token, `Authorization: Bearer <token>` on HTTP,
 *      `?token=<token>` on the WS upgrade (browsers can't set custom headers on a
 *      WebSocket handshake). Its ES256 signature and expiry are checked here on every
 *      request; Supabase's own `/auth/v1/user` is asked once per token, and again before a
 *      command if its answer is more than a minute old (RM-159, `sessionCheck.mjs`).
 *   2. Break-glass — `POST /api/local-login {password}` against a locally-hashed password
 *      (`BREAK_GLASS_PASSWORD_HASH` in server/.env, generated by
 *      `hashBreakGlassPassword.mjs`, plaintext never stored). For on-site access when
 *      Supabase Auth itself is unreachable. Issues an opaque, server-only session token —
 *      NOT a Supabase JWT, and not accepted by anything Supabase-side. The frontend must
 *      render this distinctly ("local session — LAN only, remote access unavailable"),
 *      never as an equivalent to a normal login — see src/stores/authStore.ts. It also
 *      cannot issue device commands (see `handleCommand` below) — there is no
 *      `auth.users` row to attribute a command to, and command audit rows require one.
 *
 * `POST /api/command` (Phase 6): validates via `shared/commands.mjs` (the same pure
 * contract the mock bridge uses), writes an audit row to Supabase's `commands` table using
 * the CALLER's own verified token — not this process's anon key alone, and never the
 * service-role key `ingest.mjs` holds — so RLS's `authenticated` policy is what actually
 * grants the insert, and `requested_by` is the real signed-in user. Dispatch itself stays
 * gated behind `HARDWARE_DISPATCH_ENABLED` (default unset/false): the ack is always
 * honest about what happened (`status: 'dry_run'` while closed).
 *
 * Phase 7 (lights only): with the gate open, a `switch`-class command is forwarded for
 * real to the live Node-RED flow's `POST /light/:id` (see `dispatchLight.mjs`) — the
 * same entry point the physical node-red-dashboard UI already uses. Outlets and the ACU
 * have no equivalent endpoint and stay `dry_run` even with the gate open; building those
 * is separate, later work. `GET /api/capabilities` reports that asymmetry as
 * `dispatch_classes` so the UI can name which controls are actually live, rather than
 * treating an open gate as "everything on this page now moves hardware."
 */

import './netDefaults.mjs';
import http from 'node:http';
import net from 'node:net';
import crypto from 'node:crypto';
import { URL, fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { verifyBreakGlassPassword } from './breakGlass.mjs';
import { validateCommand, buildAck, ACCEPTED_STATUS } from '../shared/commands.mjs';
import { createLivePolicy } from './livePolicy.mjs';
import { roomTargetFloorC } from '../shared/sitePolicy.mjs';
import { DEVICE_REGISTRY, TIMING, SITE } from '../shared/registry.mjs';
import { dispatchCommand, DISPATCH_CLASSES } from './dispatchLight.mjs';
import { createTuyaClient, TUYA_HOSTS } from './tuyaCloud.mjs';
import { toPublicFleet, claimedNodesFrom, assertNoSecrets } from './tuyaFleet.mjs';
import { createCredentialStore } from './credentialStore.mjs';
import { parseCredentialExport } from './credentialImport.mjs';
import { createLanPresence } from './lanPresence.mjs';
import { createDeviceSources } from './deviceSources.mjs';
import { joinMacPresence, readNeighbours, toPublicPresence } from './macPresence.mjs';
import { createAdminClient } from '../node-red-bridge/nodeRedAdmin.mjs';
import { auditedDispatch } from './auditedDispatch.mjs';
import { createJwksCache } from './jwksCache.mjs';
import { createSessionCheck } from './sessionCheck.mjs';
import { touchSignal } from './configSignal.mjs';
import { DEGRADED_NET_STATES } from '../shared/troubleStates.mjs';
import { createLocalFirstAudit, isRefusal, recoverInflight } from './auditQueue.mjs';
import { openArchive } from './archiveDb.mjs';
import { RAW_RETENTION_DAYS } from '../shared/retention.mjs';
import { bufferCount } from './ingestBuffer.mjs';
import { buildCloudDispatch } from './cloudDispatchConfig.mjs';
import { handleEnroll } from './enrollRoute.mjs';
import { handleRemove } from './removeRoute.mjs';
import { handleRebind, classForNode } from './rebindRoute.mjs';
import { installRequestMeter } from './requestMeter.mjs';

// RM-159: every request this process makes to Supabase is counted from here on, before the first is
// made. See requestMeter.mjs.
installRequestMeter({ daemon: 'ibems-proxy' });

/**
 * The Tuya cloud client, or null when the credentials are absent. Built lazily so the proxy
 * still starts without them — the cloud view is an addition, and a deployment that has not
 * been given Tuya credentials should lose that one endpoint, not fail to boot.
 *
 * TUYA_ACCESS_SECRET never leaves this process. `/api/tuya/devices` returns an allowlisted
 * shape (see tuyaFleet.mjs); the browser bundle carries the Supabase anon key and nothing else.
 */
let tuyaClient;
function getTuyaClient() {
  if (tuyaClient !== undefined) return tuyaClient;
  const accessId = process.env.TUYA_ACCESS_ID;
  const accessSecret = process.env.TUYA_ACCESS_SECRET;
  const host = TUYA_HOSTS[(process.env.TUYA_REGION ?? '').toLowerCase()];
  tuyaClient = accessId && accessSecret && host ? createTuyaClient({ accessId, accessSecret, host }) : null;
  return tuyaClient;
}

/**
 * The vendor-cloud fallback, or null when it is not configured — which is the ordinary case
 * and not an error. Built once at startup: constructing a client per command would re-read the
 * flow file and re-authenticate on a path that only runs when something is already wrong.
 */
const CLOUD_DISPATCH = buildCloudDispatch(process.env);

/**
 * Where Add Device, enrolment and rebind get device ids, local keys and protocol versions (2026-09-17).
 *
 * The vendor OpenAPI used to be the only source, and it is a time-limited subscription the operator
 * uses once per batch of pairings. So: keys imported from an export (`credentialStore.mjs`), what the
 * device network announces (`lanPresence.mjs`), and the vendor cloud only while it happens to answer.
 *
 * The presence listener binds the Tuya discovery ports with `reuseAddr`, beside Node-RED's own
 * discovery, and only listens. `LAN_PRESENCE=off` turns it off — the test harness does, and so should
 * a deployment whose proxy is not on the device segment, where it would only ever hear silence.
 */
const CREDENTIAL_STORE = createCredentialStore();
const LAN_PRESENCE = process.env.LAN_PRESENCE === 'off' ? null : createLanPresence();
LAN_PRESENCE?.start();
const DEVICE_SOURCES = createDeviceSources({ store: CREDENTIAL_STORE, cloud: getTuyaClient(), presence: LAN_PRESENCE });

/** An export of a few hundred devices is well under this; anything larger is not an export. */
const MAX_IMPORT_BODY_BYTES = 1024 * 1024;

/**
 * Which dispatch paths this building permits — see `shared/sites/<id>/site.mjs`.
 *
 * Defaulted here rather than assumed present, so a site directory written before this field
 * existed keeps behaving exactly as it did. `local-first` IS the historical behaviour: the fleet
 * is on the Pi's own segment and answers local keys, and the cloud has only ever been reached
 * after a local failure.
 */
const DISPATCH_POLICY = SITE.policy?.dispatch ?? 'local-first';

/**
 * The readings document, fetched at most once at a time.
 *
 * NOT A CACHE, and the distinction is the whole point. There is no TTL and nothing is retained
 * after the request settles: this holds only the promise for a fetch that is CURRENTLY IN
 * FLIGHT, so a caller either starts a new request or joins one that has not finished yet. The
 * next command after it settles fetches afresh.
 *
 * Why it exists: the Control page's "all off" fires one command per socket with no await and no
 * concurrency cap — fourteen for the outlets, seven for the lights — and each one independently
 * asked the bridge for the whole document. One button therefore put fourteen simultaneous HTTP
 * requests through the same Node-RED event loop that services the tuya nodes. Measured
 * 2026-09-03 on a fleet already flapping at the access point, which is to say the app was
 * amplifying the fault it was being used to diagnose.
 */
let readingsInFlight = null;

function fetchReadingsOnce() {
  if (readingsInFlight) return readingsInFlight;
  readingsInFlight = (async () => {
    try {
      const res = await fetch(`http://${BRIDGE_HOST}:${BRIDGE_PORT}/api/readings/latest`, {
        signal: AbortSignal.timeout(5000),
      });
      if (!res.ok) return null;
      const rows = await res.json();
      return Array.isArray(rows) ? rows : null;
    } catch {
      return null;
    } finally {
      // Cleared in `finally` so a failed fetch cannot wedge every later command onto a rejected
      // promise — the next caller starts a fresh request rather than inheriting this one's fate.
      readingsInFlight = null;
    }
  })();
  return readingsInFlight;
}

/**
 * The bridge own view of whether a device is reachable, used to stop a local dispatch claiming
 * success it cannot have had. Returns `true`/`false`, or `null` when the bridge could not be
 * asked — see `dispatchCommand`, which treats `null` as "attempt local anyway" on purpose.
 *
 * Deliberately unmemoised ACROSS TIME. This is read on a user-initiated command and the whole
 * point is that it is current: a cached "online" from thirty seconds ago is the same fabrication
 * the HTTP 2xx was. Sharing one in-flight request between commands issued in the same instant
 * gives up nothing there — that request would have been made anyway, and every one of those
 * callers would have accepted its answer.
 */
async function readDeviceOnline(device) {
  const rows = await fetchReadingsOnce();
  if (!rows) return null;
  const row = rows.find((r) => r.device_id === device.id);
  return row ? row.online === true : null;
}

/**
 * The same read, returning the whole row — the aircon needs its last COMMANDED mode, fan and swing
 * to turn a setpoint-only command into a full state (`shared/acState.mjs`). `null` when the bridge
 * could not be asked, which the dispatcher treats exactly as `readDeviceOnline`'s `null`.
 */
async function readDeviceLatest(device) {
  const rows = await fetchReadingsOnce();
  if (!rows) return null;
  return rows.find((r) => r.device_id === device.id) ?? null;
}

/** The meters whose two channels the bridge demuxes: `channel_demux` in the site's config. */
const DEMUXED_DEVICE_IDS = new Set((SITE.channel_demux ?? []).flatMap((pair) => pair.devices));

/**
 * A setting on a demuxed meter goes to the clamp this circuit is on RIGHT NOW, or nowhere — RM-152.
 *
 * The bridge swaps every per-channel dp on READ while the meter reports its clamps swapped
 * (`shared/channelDemux.mjs`), but the write route (`node-red-bridge/capabilityRoutePlan.mjs`)
 * addresses the physical dp. So during a swapped spell a power limit written for C.O Yellow would
 * land on the lighting branch's clamp: the other circuit, with no error anywhere. Refused unless the
 * latest reading says `direct`. An assignment that cannot be read is refused too, because it cannot
 * be checked. Refused before anything is recorded, like the other validation refusals.
 */
async function channelSwapRefusal(device, cmd) {
  if (cmd.action !== 'set' || !DEMUXED_DEVICE_IDS.has(device.id)) return null;
  const latest = await readDeviceLatest(device).catch(() => null);
  const assignment = latest?.channel_map?.assignment ?? latest?.capabilities?.channel_map?.assignment ?? null;
  if (assignment === 'direct') return null;
  return {
    error: 'channels_not_direct',
    code: 'channels_not_direct',
    detail:
      assignment === 'swapped'
        ? 'This meter is reporting its two clamps swapped right now, so a setting sent for this circuit would reach the other one. Nothing was sent. Try again once the meter reads direct.'
        : 'Could not confirm which clamp this meter is attributing to this circuit right now, so nothing was sent.',
  };
}

/**
 * Whether the aircon's full state can reach the vendor cloud from here — for the Control page, so
 * it can say "this needs the cloud, and there is none" before somebody presses Send rather than
 * after. `null` at a site with no aircon at all.
 */
async function acuCloudRoute() {
  if (!DEVICE_REGISTRY.some((d) => d.class === 'acu_ir')) return null;
  if (DISPATCH_POLICY === 'local-only') return 'local-only';
  if (!CLOUD_DISPATCH?.client || !CLOUD_DISPATCH.acRemoteId) return 'unconfigured';
  const remote = await CLOUD_DISPATCH.acRemoteId().catch(() => ({ ok: false }));
  return remote.ok ? 'ready' : 'unresolved';
}

const PROXY_PORT = Number(process.env.PROXY_PORT) || 8080;
const BRIDGE_HOST = process.env.BRIDGE_HOST || '127.0.0.1';
const BRIDGE_PORT = Number(process.env.BRIDGE_PORT) || 1880;
// How long to wait on an upstream that has accepted the connection but not answered.
// Overridable only so the test suite can exercise the hang path without waiting 10s for it;
// the default is the same budget every other bridge call in this repo uses.
const BRIDGE_TIMEOUT_MS = Number(process.env.BRIDGE_TIMEOUT_MS) || TIMING.FETCH_TIMEOUT_MS;
const SUPABASE_URL = process.env.SUPABASE_URL;
// The ANON key, not service-role — verifying a user's own token needs no elevated
// privilege, and this process's whole point is to hold less power than ingest.mjs, not more.
const SUPABASE_ANON_KEY = process.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY;

/**
 * The live operating policy — RM-038. `SITE.policy` is the build-time declaration and the
 * fallback; the `sites` row is what an operator can actually change. See `server/livePolicy.mjs`
 * for why the fallback runs in that direction and not the other.
 *
 * NOTE the deliberate asymmetry with `DISPATCH_POLICY` above, which is still read from the build
 * and NOT from here. Whether commands may leave the building for a vendor cloud is not something
 * a settings screen may change: phase26's function cannot write that key, and reading it live
 * would create an expectation that it can.
 */
const livePolicy = createLivePolicy({
  buildPolicy: SITE.policy ?? {},
  siteId: SITE.id,
  supabaseUrl: SUPABASE_URL,
  supabaseKey: SUPABASE_ANON_KEY,
});
const BREAK_GLASS_PASSWORD_HASH = process.env.BREAK_GLASS_PASSWORD_HASH;
/**
 * How old an online answer about a session may be before a COMMAND asks again, and how long the
 * old path keeps one for a token the signing keys cannot judge. Tunable only so a test need not
 * wait out a real minute — see SCHEDULE_REFRESH_MS in scheduler.mjs for the same reason.
 */
const SUPABASE_VERIFY_CACHE_MS = Number(process.env.PROXY_SESSION_RECHECK_MS) || 60_000;

/**
 * OFFLINE OPERATION. The Tuya fleet is local — the devices sit on the Pi's own segment and
 * answer local keys — so commanding them needs no internet whatsoever. Two things did need it
 * anyway, and between them they reduced the offline command window to zero: this file verified
 * every session by calling Supabase, and `auditedDispatch` wrote the audit row there before
 * dispatching. A WAN outage therefore removed control of the whole building while the device
 * layer sat there working.
 *
 * Neither safety property is being relaxed. Sessions are still verified and commands are still
 * recorded before a relay moves; both simply gain an implementation that does not require a
 * link to the internet. See jwtVerify.mjs and auditQueue.mjs for the limits of each.
 */
const JWKS_URL = SUPABASE_URL ? `${SUPABASE_URL}/auth/v1/.well-known/jwks.json` : null;
const JWKS_ISSUER = SUPABASE_URL ? `${SUPABASE_URL}/auth/v1` : null;
const JWKS_CACHE_PATH = process.env.JWKS_CACHE_PATH || join(dirname(fileURLToPath(import.meta.url)), 'data', 'jwks.json');
const JWKS_REFRESH_MS = 6 * 60 * 60 * 1000; // 6h — signing keys rotate rarely
const COMMAND_BUFFER_PATH = process.env.COMMAND_AUDIT_BUFFER_PATH || join(dirname(fileURLToPath(import.meta.url)), 'data', 'command-audit-buffer.ndjson');
/**
 * The scheduler records to its own file (one writer per file — see auditQueue.mjs), but the
 * backlog reported to the UI has to cover both. "The audit trail is behind" is one fact about
 * the system, and a scheduled command waiting to upload is exactly as behind as a manual one.
 */
const SCHEDULER_BUFFER_PATH = process.env.SCHEDULER_AUDIT_BUFFER_PATH || join(dirname(fileURLToPath(import.meta.url)), 'data', 'command-audit-buffer-scheduler.ndjson');
/**
 * RM-157: where a person's command is recorded before its relay is asked to move. This process's
 * alone — `ingest.mjs` drains COMMAND_BUFFER_PATH, never this — and normally empty again within a
 * second, once the record has gone up. See `createLocalFirstAudit`.
 */
const COMMAND_INFLIGHT_PATH = process.env.COMMAND_AUDIT_INFLIGHT_PATH || join(dirname(fileURLToPath(import.meta.url)), 'data', 'command-audit-inflight.ndjson');
/** RM-159: touched to tell the scheduler its configuration changed. This process is its only writer. See configSignal.mjs. */
const CONFIG_SIGNAL_PATH = process.env.CONFIG_SIGNAL_PATH || join(dirname(fileURLToPath(import.meta.url)), 'data', 'config-changed.signal');
function signalConfigChanged(why) {
  if (!touchSignal(CONFIG_SIGNAL_PATH)) console.error(`[ibems-proxy] could not tell the scheduler about ${why} (${CONFIG_SIGNAL_PATH}); it reads again within its safety-net interval`);
}
{
  // A record left behind by a run that stopped mid-command is not lost: it goes to the outage
  // queue as it stood, `dispatching` if nobody saw how the command went.
  //
  // Never fatal. A proxy that will not start takes every READ down with it; one whose record file
  // is unusable still serves the building, and refuses each command at the record instead.
  try {
    const recovered = recoverInflight(COMMAND_INFLIGHT_PATH, COMMAND_BUFFER_PATH);
    if (recovered) console.error(`[ibems-proxy] ${recovered} command record(s) left on the edge by the last run, queued for upload`);
  } catch (err) {
    console.error(`[ibems-proxy] could not recover command records from ${COMMAND_INFLIGHT_PATH}: ${err.message}`);
  }
}

const jwks = JWKS_URL ? createJwksCache({ url: JWKS_URL, cachePath: JWKS_CACHE_PATH }) : null;

const LOCAL_SESSION_TTL_MS = 12 * 60 * 60 * 1000; // 12h
// Closed by default, mirroring node-red-bridge/deploy.mjs's --apply-only-with-explicit-
// intent pattern. Phase 7 is the only phase allowed to flip this in a real deployment.
const HARDWARE_DISPATCH_ENABLED = process.env.HARDWARE_DISPATCH_ENABLED === 'true';
// Shared secret with the live Node-RED flow's "Auth + validate" function (POST
// /light/:id) — see dispatchLightCommand below. Only ever needed when the gate above is
// open; local/mock-bridge dev never sets HARDWARE_DISPATCH_ENABLED, so this stays unset there.
const LIGHT_API_TOKEN = process.env.LIGHT_API_TOKEN || null;



if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('[ibems-proxy] SUPABASE_URL and VITE_SUPABASE_ANON_KEY are required — see server/.env.example');
  process.exit(1);
}
if (!BREAK_GLASS_PASSWORD_HASH) {
  console.warn('[ibems-proxy] BREAK_GLASS_PASSWORD_HASH not set — /api/local-login will 501 until it is (see server/hashBreakGlassPassword.mjs)');
}
// Hard fail-fast, not a warn-and-degrade like BREAK_GLASS_PASSWORD_HASH above: a proxy
// that believes it can dispatch to real hardware but has no way to authenticate to the
// light endpoint is a dangerous half-configuration, not a safe degraded mode.
if (HARDWARE_DISPATCH_ENABLED && !LIGHT_API_TOKEN) {
  console.error(
    '[ibems-proxy] HARDWARE_DISPATCH_ENABLED=true but LIGHT_API_TOKEN is unset — refusing to start. ' +
      'A hardware-dispatch-capable proxy with no way to authenticate to the light endpoint is a dangerous ' +
      'half-configuration, not a safe degraded mode. Set LIGHT_API_TOKEN in server/.env, or leave HARDWARE_DISPATCH_ENABLED unset/false.',
  );
  process.exit(1);
}

// --- local (break-glass) sessions: opaque token -> expiry, in-memory only. Restarting
// this process invalidates every local session — acceptable for a rare, on-site fallback. ---
const localSessions = new Map();

function issueLocalSession() {
  const token = crypto.randomBytes(32).toString('hex');
  localSessions.set(token, Date.now() + LOCAL_SESSION_TTL_MS);
  return token;
}
function isValidLocalSession(token) {
  const exp = localSessions.get(token);
  if (!exp) return false;
  if (Date.now() > exp) {
    localSessions.delete(token);
    return false;
  }
  return true;
}
setInterval(() => {
  const now = Date.now();
  for (const [t, exp] of localSessions) if (now > exp) localSessions.delete(t);
}, 60_000).unref();

// --- Supabase sessions — RM-159: asked about online once per token, see sessionCheck.mjs ------

/**
 * Supabase's own answer about a token: `{answered: true, ok, userId}`, or `{answered: false}` when
 * the question could not be put — no answer at all, or one that does not judge the token. RM-157:
 * only a 4xx about the token is an answer. A project restricted for a quota answers 402, a rate
 * limit 429, an outage 5xx; none of them says this session is invalid, so they take the offline
 * path rather than a refusal that signs everybody out.
 */
async function askSupabaseAboutSession(token) {
  try {
    const res = await fetch(`${SUPABASE_URL}/auth/v1/user`, {
      headers: { Authorization: `Bearer ${token}`, apikey: SUPABASE_ANON_KEY },
      signal: AbortSignal.timeout(5000),
    });
    if (res.ok) {
      const body = await res.json();
      return { answered: true, ok: true, userId: typeof body?.id === 'string' ? body.id : null };
    }
    if (isRefusal(res.status)) return { answered: true, ok: false, userId: null };
    return { answered: false, detail: `auth answered ${res.status} without judging the token` };
  } catch (err) {
    return { answered: false, detail: String(err?.message ?? err) };
  }
}

const sessionCheck = createSessionCheck({
  askOnline: askSupabaseAboutSession,
  keys: () => (jwks ? jwks.keys() : []),
  refreshKeys: () => (jwks ? jwks.refresh() : null),
  issuer: JWKS_ISSUER,
  freshMs: SUPABASE_VERIFY_CACHE_MS,
  legacyCacheMs: SUPABASE_VERIFY_CACHE_MS,
  log: (line) => console.error(`[ibems-proxy] ${line}`),
});
setInterval(() => sessionCheck.sweep(), 60_000).unref();

/**
 * `{ok, userId, offline?}` — `userId` is `auth.users.id`, needed by `handleCommand` to attribute a
 * command's audit row to a real user. `fresh` is for commands: an online answer no older than a minute.
 */
function verifySupabaseSession(token, { fresh = false } = {}) {
  return sessionCheck.check(token, { fresh });
}

async function isAuthorized(token) {
  if (!token) return false;
  if (isValidLocalSession(token)) return true;
  return (await verifySupabaseSession(token)).ok;
}

function tokenFromRequest(req, url) {
  const header = req.headers['authorization'];
  if (header?.startsWith('Bearer ')) return header.slice(7);
  return url.searchParams.get('token') || null;
}

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'content-type, authorization',
  'Access-Control-Max-Age': '600',
};

function sendJson(res, status, body) {
  res.writeHead(status, { 'Content-Type': 'application/json', ...CORS_HEADERS });
  res.end(JSON.stringify(body));
}

/**
 * RM-148: the edge's raw archive, READ-ONLY. The ingest daemon is its only writer; this process only
 * answers from it, for history older than the cloud's raw window (`shared/retention.mjs`). Opened on
 * first use and kept open — a WAL reader never blocks the writer — and dropped on any error so the
 * next request opens it afresh.
 */
const ARCHIVE_PATH = process.env.ARCHIVE_DB_PATH || join(dirname(fileURLToPath(import.meta.url)), 'data', 'archive', 'archive.sqlite');
/** A month plus a day: the longest report period, whichever way its window falls. One device's minutes for it are about 45,000 rows. */
const ARCHIVE_MAX_WINDOW_MS = 32 * 24 * 3600 * 1000;
let archiveReader = null;

function readArchive(fn) {
  try {
    archiveReader ??= openArchive(ARCHIVE_PATH, { readOnly: true });
    return fn(archiveReader);
  } catch (err) {
    try { archiveReader?.close(); } catch { /* reopened on the next request */ }
    archiveReader = null;
    throw err;
  }
}

function handleArchiveStatus(res) {
  try {
    const s = readArchive((a) => a.stats());
    return sendJson(res, 200, { available: true, oldest: s.oldest, newest: s.newest, readings: s.readings, bytes: s.bytes, hot_days: RAW_RETENTION_DAYS });
  } catch (err) {
    return sendJson(res, 200, { available: false, reason: String(err?.message ?? err).split(' — ')[0], hot_days: RAW_RETENTION_DAYS });
  }
}

/** One device's minute readings for a window, in the shape `src/lib/readingsExport.ts` exports. */
function handleArchiveReadings(url, res) {
  const deviceId = url.searchParams.get('device_id');
  const sinceMs = Date.parse(url.searchParams.get('since') ?? '');
  const untilMs = Date.parse(url.searchParams.get('until') ?? '');
  if (!deviceId || Number.isNaN(sinceMs) || Number.isNaN(untilMs) || untilMs <= sinceMs) {
    return sendJson(res, 400, { error: 'bad_window', detail: 'device_id, since and until (ISO instants, since before until) are required' });
  }
  if (untilMs - sinceMs > ARCHIVE_MAX_WINDOW_MS) {
    return sendJson(res, 400, { error: 'window_too_long', detail: 'at most 32 days of one device per request' });
  }
  let rows;
  try {
    rows = readArchive((a) => [...a.rowsBetween('readings', { sinceMs, untilMs, deviceId })]
      .map((r) => ({ ts: r.ts, voltage: r.voltage, current: r.current, power_w: r.power_w, energy_kwh_today: r.energy_kwh_today, online: r.online })));
  } catch (err) {
    return sendJson(res, 503, { error: 'archive_unavailable', detail: String(err?.message ?? err).split(' — ')[0] });
  }
  return sendJson(res, 200, { device_id: deviceId, rows });
}

/** A bell asks for minutes; a day is generous, and keeps one response small. */
const ANOMALY_MAX_WINDOW_MS = 24 * 60 * 60 * 1000;
const ANOMALY_COLUMNS = ['device_id', 'ts', 'metric', 'value', 'baseline_mean', 'baseline_stddev', 'z_score', 'iqr_lower', 'iqr_upper', 'method', 'sample_count'];

/**
 * `GET /api/archive/anomalies?since=<ISO>` — RM-158. The alert bell's recent anomalies, newest first,
 * in the columns `src/lib/supabaseAnomalies.ts` asks the cloud for.
 *
 * Every open browser asked Supabase this once a minute, and a browser asking Supabase sends a CORS
 * OPTIONS first: two lines in the project's log per minute per screen, about 2,880 a day for the
 * kiosk alone, when log ingestion was over the Free plan's 1 GB. Ingest archives each anomaly on the
 * edge the minute it finds it, before it uploads it, so the edge holds the same rows, sooner.
 */
function handleArchiveAnomalies(url, res) {
  const sinceMs = Date.parse(url.searchParams.get('since') ?? '');
  const nowMs = Date.now();
  if (Number.isNaN(sinceMs) || sinceMs > nowMs) {
    return sendJson(res, 400, { error: 'bad_window', detail: 'since (an ISO instant, not in the future) is required' });
  }
  if (nowMs - sinceMs > ANOMALY_MAX_WINDOW_MS) {
    return sendJson(res, 400, { error: 'window_too_long', detail: 'at most one day of anomalies per request' });
  }
  let rows;
  try {
    // A minute past now, so a row stamped by a clock slightly ahead of this one is not missed.
    rows = readArchive((a) => [...a.rowsBetween('anomalies', { sinceMs, untilMs: nowMs + 60_000 })]
      .map((r) => Object.fromEntries(ANOMALY_COLUMNS.map((c) => [c, r[c] ?? null]))));
  } catch (err) {
    return sendJson(res, 503, { error: 'archive_unavailable', detail: String(err?.message ?? err).split(' — ')[0] });
  }
  return sendJson(res, 200, { rows: rows.reverse() });
}

/** A week of trouble plus the day read before it (TROUBLE_FETCH_MS), and a day's slack. */
const TROUBLE_MAX_WINDOW_MS = 9 * 24 * 60 * 60 * 1000;

/** `since` as an instant not in the future and at most `maxMs` ago, or a 400 already sent. */
function windowSince(url, res, maxMs, label) {
  const sinceMs = Date.parse(url.searchParams.get('since') ?? '');
  const nowMs = Date.now();
  if (Number.isNaN(sinceMs) || sinceMs > nowMs) {
    sendJson(res, 400, { error: 'bad_window', detail: 'since (an ISO instant, not in the future) is required' });
    return null;
  }
  if (nowMs - sinceMs > maxMs) {
    sendJson(res, 400, { error: 'window_too_long', detail: label });
    return null;
  }
  return { sinceMs, nowMs };
}

function archiveUnavailable(res, err) {
  return sendJson(res, 503, { error: 'archive_unavailable', detail: String(err?.message ?? err).split(' — ')[0] });
}

/**
 * `GET /api/archive/trouble?since=<ISO>` — RM-159. The fault, power-warning and no-network minutes
 * `src/lib/supabaseCapabilityHistory.ts` asked the cloud for: three queries every five minutes from
 * every open screen, each with a CORS OPTIONS, about 1,700 lines a day in the project's log for the
 * kiosk alone. The edge holds every one of those minutes, sooner.
 */
function handleArchiveTrouble(url, res) {
  const w = windowSince(url, res, TROUBLE_MAX_WINDOW_MS, 'at most nine days of trouble per request');
  if (!w) return undefined;
  try {
    // A minute past now, as for the anomalies: a row stamped by a clock slightly ahead is not missed.
    return sendJson(res, 200, readArchive((a) => a.troubleRows({ sinceMs: w.sinceMs, untilMs: w.nowMs + 60_000, degradedNetStates: DEGRADED_NET_STATES })));
  } catch (err) {
    return archiveUnavailable(res, err);
  }
}

/**
 * `GET /api/archive/connectivity?hours=N` — RM-159. `device_connectivity` (supabase/phase15), which every
 * open screen called every five minutes for the flapping badge, over the edge's own minutes. Same clamp
 * (1..168 hours) and the same `expected_samples`.
 */
function handleArchiveConnectivity(url, res) {
  const asked = Number(url.searchParams.get('hours') ?? 24);
  const hours = Math.max(1, Number.isFinite(asked) ? Math.trunc(asked) : 24);
  // The archive is read on this process's one thread. A day takes about 140 ms on the Pi and a week about
  // 1.2 s (measured 2026-10-05), long enough to hold up a command. The app asks for a day; a longer window
  // is refused here, and the browser asks the cloud's `device_connectivity` instead.
  if (hours > CONNECTIVITY_MAX_HOURS) {
    return sendJson(res, 400, { error: 'window_too_long', detail: `at most ${CONNECTIVITY_MAX_HOURS} hours from the edge; ask the cloud for longer` });
  }
  const now = Date.now();
  // One answer a minute is shared: the bell and the Devices page, and every open screen, ask the same thing
  // every five minutes, and a day's figure does not move in a minute.
  if (!connectivityCache || connectivityCache.hours !== hours || now - connectivityCache.at >= CONNECTIVITY_CACHE_MS) {
    try {
      const rows = readArchive((a) => a.connectivity({ sinceMs: now - hours * 3600_000 }));
      connectivityCache = { hours, at: now, rows: rows.map((r) => ({ ...r, expected_samples: hours * 60 })) };
    } catch (err) {
      return archiveUnavailable(res, err);
    }
  }
  return sendJson(res, 200, { rows: connectivityCache.rows });
}

const CONNECTIVITY_MAX_HOURS = 48;
const CONNECTIVITY_CACHE_MS = 60_000;
let connectivityCache = null;

/** `readings_buckets`' own cap (supabase/phase9), so the edge refuses what the cloud would. */
const BUCKETS_MAX = 900;

/**
 * `GET /api/archive/buckets?device_id=&since=&bucket_s=` — RM-159. `readings_buckets` (phase9) for the
 * Analytics week: one device's minutes since `since`, averaged per bucket. Left open on that range, the
 * page asked the cloud once per device every five minutes — about 6,300 lines a day.
 */
function handleArchiveBuckets(url, res) {
  const deviceId = url.searchParams.get('device_id');
  const bucketSeconds = Number(url.searchParams.get('bucket_s'));
  if (!deviceId || !Number.isInteger(bucketSeconds) || bucketSeconds < 60) {
    return sendJson(res, 400, { error: 'bad_request', detail: 'device_id and bucket_s (whole seconds, at least 60) are required' });
  }
  const w = windowSince(url, res, ARCHIVE_MAX_WINDOW_MS, 'at most 32 days of one device per request');
  if (!w) return undefined;
  if (Math.ceil((w.nowMs - w.sinceMs) / 1000 / bucketSeconds) > BUCKETS_MAX) {
    return sendJson(res, 400, { error: 'too_many_buckets', detail: `over the ${BUCKETS_MAX}-bucket cap; use a larger bucket_s` });
  }
  try {
    return sendJson(res, 200, { device_id: deviceId, rows: readArchive((a) => a.buckets({ deviceId, sinceMs: w.sinceMs, untilMs: w.nowMs + 60_000, bucketSeconds })) });
  } catch (err) {
    return archiveUnavailable(res, err);
  }
}

async function readJsonBody(req) {
  let raw = '';
  for await (const chunk of req) raw += chunk;
  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

/**
 * `POST /api/credentials/import` — `{content, complete?}`, the text of a key-extraction tool's export.
 *
 * Authenticated like enrolment, and like enrolment not behind HARDWARE_DISPATCH_ENABLED: storing a
 * key moves nothing. The reply reports counts and per-row problems; it never carries a key, and the
 * problems name rows by name or id only (`credentialImport.mjs`).
 *
 * `complete` is the operator saying the export lists EVERY device in the account. Only then may a
 * device's absence from it count towards calling a flow node orphaned — see `deviceSources.mjs`.
 */
async function handleCredentialImport(req, res) {
  let raw = '';
  let size = 0;
  let oversize = false;
  // Drained to the end rather than cut off, so the client reads the 413 instead of a reset socket.
  for await (const chunk of req) {
    size += chunk.length;
    if (size > MAX_IMPORT_BODY_BYTES) oversize = true;
    else raw += chunk;
  }
  if (oversize) return sendJson(res, 413, { ok: false, problems: ['the export is larger than any device export should be'] });

  let body;
  try {
    body = JSON.parse(raw);
  } catch {
    return sendJson(res, 400, { ok: false, problems: ['malformed request body'] });
  }
  if (typeof body?.content !== 'string') return sendJson(res, 400, { ok: false, problems: ['content must be the export text'] });

  const parsed = parseCredentialExport(body.content);
  if (!parsed.format || parsed.devices.length === 0) {
    // `error` as well as `problems`: the browser's fetchJson surfaces only `error` from a non-2xx reply.
    const reason = parsed.problems[0] ?? 'no row had both a device id and a usable local key';
    return sendJson(res, 422, { ok: false, error: reason, format: parsed.format, added: 0, updated: 0, total: CREDENTIAL_STORE.publicView().length, complete: false, problems: parsed.problems.length ? parsed.problems : [reason] });
  }
  const complete = body.complete === true;
  const result = CREDENTIAL_STORE.importDevices(parsed.devices, { source: `import:${parsed.format}`, complete });
  console.log(`[ibems-proxy] credential import: ${parsed.devices.length} device(s), added ${result.added}, updated ${result.updated}, complete=${complete}, ${parsed.problems.length} problem(s)`);
  return sendJson(res, 200, assertNoSecrets({ ok: true, format: parsed.format, ...result, complete, problems: parsed.problems }));
}

async function handleLocalLogin(req, res) {
  if (!BREAK_GLASS_PASSWORD_HASH) return sendJson(res, 501, { error: 'break_glass_not_configured' });
  const body = await readJsonBody(req);
  const password = body?.password;
  if (!verifyBreakGlassPassword(password, BREAK_GLASS_PASSWORD_HASH)) {
    return sendJson(res, 401, { error: 'invalid_password' });
  }
  const token = issueLocalSession();
  sendJson(res, 200, { token, expires_in: LOCAL_SESSION_TTL_MS / 1000, mode: 'local' });
}

/** Forwards to the real bridge, stripping the proxy-only `token` query param first — the
 * bridge has no concept of it, and for GET history requests the *other* query params
 * (device_id, range) still need to pass through untouched. */
function proxyHttp(req, res, url) {
  const upstream = new URL(url);
  upstream.searchParams.delete('token');

  const proxyReq = http.request(
    { hostname: BRIDGE_HOST, port: BRIDGE_PORT, path: upstream.pathname + upstream.search, method: req.method, headers: { ...req.headers, host: `${BRIDGE_HOST}:${BRIDGE_PORT}` } },
    (proxyRes) => {
      // Node-RED's httpNodeCors already sends its own `access-control-*` headers (all
      // lowercase — Node always normalizes incoming header names). Spreading those
      // alongside our own CORS_HEADERS (capitalized keys) used to produce a response with
      // the SAME header twice under different casing — e.g. two Access-Control-Allow-Origin
      // values. That's invalid per the Fetch/CORS spec, and a browser rejects the response
      // outright with a fast, silent "Failed to fetch" — no server-side error, no slow
      // network involved. curl doesn't enforce CORS at all, so every curl-based check
      // during this bug's investigation looked fine; only a real browser could ever have
      // shown it. Strip the upstream's CORS headers before applying ours so exactly one
      // version of each survives.
      const headers = { ...proxyRes.headers };
      for (const key of Object.keys(headers)) {
        if (key.toLowerCase().startsWith('access-control-')) delete headers[key];
      }
      res.writeHead(proxyRes.statusCode, { ...headers, ...CORS_HEADERS });
      proxyRes.pipe(res);
    }
  );
  // A bridge that REFUSES a connection raises 'error' and is handled below. A bridge that
  // ACCEPTS and then hangs raises nothing at all, and without this timeout the request would
  // sit open indefinitely, holding a socket on both legs. Node-RED under a Tuya
  // discovery-retry storm is exactly the process that hangs rather than refuses — the
  // condition that produced ~104,500 journal lines an hour and needed
  // server/nodered-log-ratelimit.conf. The client's own abort would free the browser side,
  // but never this one.
  proxyReq.setTimeout(BRIDGE_TIMEOUT_MS, () => {
    proxyReq.destroy(new Error(`bridge did not respond within ${BRIDGE_TIMEOUT_MS}ms`));
  });

  proxyReq.on('error', (err) => {
    // The upstream detail goes to the journal, not to the caller. `String(err)` on a
    // Supabase or bridge error can carry project-identifying strings, and the caller has no
    // use for them — dispatchLight.mjs's 502 path already draws this line; the two
    // bridge-facing paths here did not.
    console.error(`[ibems-proxy] upstream ${req.method} ${upstream.pathname} failed: ${String(err)}`);
    // A hang that trips the timeout above may already have had headers written if the
    // bridge started responding and then stalled mid-body; there is no second status line
    // to send in that case, only a socket to close.
    if (res.headersSent) return res.destroy();
    sendJson(res, 502, { error: 'bridge_unreachable', detail: 'The Node-RED bridge did not respond.' });
  });
  req.pipe(proxyReq);
}

/**
 * `POST /api/command` — architecture plan Phase 6. `token` has already passed the generic
 * `isAuthorized` gate (so it's either a valid break-glass session or a valid Supabase
 * token) by the time this is called; this function applies the STRICTER rule commands
 * need on top of that.
 */
async function handleCommand(req, res, token) {
  // RM-157: how long the person waited, journaled once per command — the number the amber
  // "Switching" pulse makes visible, and the one the local-first record exists to shorten.
  const startedMs = Date.now();
  const session = await verifySupabaseSession(token, { fresh: true });
  if (!session.ok || !session.userId) {
    // isAuthorized() already accepted this token, so if it's not a real Supabase session
    // it must be a valid break-glass one — reject with a reason the frontend can render
    // distinctly from "not logged in at all" (401).
    return sendJson(res, 403, {
      error: 'break_glass_cannot_command',
      detail: 'Local/break-glass sessions are view-only — device commands require a real Supabase-authenticated session.',
    });
  }

  const body = await readJsonBody(req);
  // This building's own bounds — e.g. the minimum aircon setpoint the operator permits, which is
  // narrower than what the IR library can physically send. Read synchronously from the cache so a
  // command never waits on a round trip; `refresh()` runs in the background and, on failure,
  // leaves the last known floor in force rather than none. Read with this caller's session (RM-158).
  void livePolicy.refresh(false, { token });
  const validated = validateCommand(body, DEVICE_REGISTRY, livePolicy.current());
  if (!validated.ok) {
    return sendJson(res, validated.status, { error: validated.error, code: validated.code });
  }

  const { cmd } = validated;
  const device = DEVICE_REGISTRY.find((d) => d.id === cmd.device_id); // already validated to exist
  const swapped = await channelSwapRefusal(device, cmd);
  if (swapped) return sendJson(res, 409, swapped);
  const acceptedAtMs = Date.now();
  const ack = buildAck(cmd, acceptedAtMs);

  // The audit row is written with the CALLER's own token, not SUPABASE_ANON_KEY alone —
  // RLS's `auth.role() = 'authenticated'` check needs the request to actually carry a
  // signed-in user's session for PostgREST to grant the insert.
  const sbCommands = (path, init) =>
    fetch(`${SUPABASE_URL}/rest/v1/commands${path}`, {
      ...init,
      headers: { Authorization: `Bearer ${token}`, apikey: SUPABASE_ANON_KEY, 'Content-Type': 'application/json', ...init.headers },
      signal: AbortSignal.timeout(5000),
    });

  // Which classes really reach hardware is declared once, in dispatchLight.mjs, next to the
  // routing that implements it — so what /api/capabilities advertises and what this function
  // will actually do cannot drift apart. The record-then-act ordering is shared with
  // scheduler.mjs via auditedDispatch, so the two paths cannot disagree about what an
  // unrecorded command means: it is never dispatched.
  //
  // RM-157: recorded on the EDGE first, then uploaded once, after the relay has been asked.
  // The click used to wait for two Supabase round trips — the row before, the outcome after —
  // about 0.43 s each from here, and up to the 5 s timeout on a bad evening. See
  // `createLocalFirstAudit` and docs/adr/ADR-0014-commands-recorded-on-the-edge.md.
  const uploadRow = async (row) => {
    try {
      // `return=minimal`: nothing is patched afterwards, so no id is needed back.
      const res = await sbCommands('', { method: 'POST', headers: { Prefer: 'return=minimal' }, body: JSON.stringify(row) });
      if (!res.ok) return { ok: false, unreachable: !isRefusal(res.status), detail: `HTTP ${res.status} ${await res.text().catch(() => '')}` };
      return { ok: true };
    } catch (err) {
      return { ok: false, unreachable: true, detail: String(err) };
    }
  };
  const audit = createLocalFirstAudit({ inflightPath: COMMAND_INFLIGHT_PATH, bufferPath: COMMAND_BUFFER_PATH, upload: uploadRow });

  /**
   * A below-policy setpoint is RECORDED, not refused — RM-068.
   *
   * `validateCommand` used to return 400 `below_policy_floor` for these and the command never
   * happened, so there was nothing to record. Now it accepts and warns, which means the audit
   * trail is the only place the fact survives. Appending it to the note rather than adding a
   * column keeps it working on a database that has not been migrated for it, and the note is
   * already where this table carries prose.
   */
  const warningNote = (cmd.warnings ?? []).map((w) => w.detail).join('; ');

  const outcome = await auditedDispatch({
    device,
    cmd,
    note: warningNote ? `${ack.note} — ${warningNote}` : ack.note,
    auditRow: {
      command_id: cmd.command_id ?? null,
      device_id: cmd.device_id,
      socket: cmd.socket ?? null,
      action: cmd.action,
      target: cmd.target,
      requested_by: session.userId,
      accepted_at: new Date(acceptedAtMs).toISOString(),
      confirmed: false,
      confirmation: 'none',
      source: 'ibems-app',
      /**
       * Added ONLY for a capability write, and that is a sequencing decision rather than a
       * tidiness one. These two columns and `action = 'set'` arrive with
       * `supabase/phase29_command_capability.sql`, which is applied by hand. Naming a column
       * PostgREST does not have makes it reject the insert, so:
       *
       *   - a relay command's row is byte-identical to what it has always been, and cannot be
       *     broken by this change whether or not the migration has run;
       *   - a capability write before the migration fails at the AUDIT INSERT, and
       *     `auditedDispatch` refuses to dispatch anything it could not record first. The
       *     failure mode is a refused command, never an unrecorded one that moved hardware.
       *
       * So the write path is safe by construction until the migration lands, rather than safe
       * because someone remembered to apply it in the right order.
       */
      ...(cmd.action === 'set'
        ? { capability: cmd.capability, capability_value: cmd.value }
        : {}),
    },
    dispatchEnabled: HARDWARE_DISPATCH_ENABLED,
    dispatchClasses: DISPATCH_CLASSES,
    dispatch: (d, c) => dispatchCommand(d, c, {
      bridgeHost: BRIDGE_HOST,
      bridgePort: BRIDGE_PORT,
      lightApiToken: LIGHT_API_TOKEN,
      cloud: CLOUD_DISPATCH,
      // The site's own answer to "may a vendor be in this building's control path at all".
      // `local-first` (the default) is what this code has always done; `local-only` makes the
      // refusal explicit rather than relying on nobody having set the credentials.
      policy: DISPATCH_POLICY,
      readOnline: readDeviceOnline,
      // The aircon: its last commanded state fills a partial command, and an unverified local IR
      // library sends ON states through the cloud first. See dispatchLight.mjs `dispatchAircon`.
      readLatest: readDeviceLatest,
      localIrVerified: SITE.aircon?.local_ir_verified === true,
    }),
    insertAudit: audit.insertAudit,
    updateAudit: audit.updateAudit,
    log: (msg) => console.error(`[ibems-proxy] ${msg}`),
  });

  // The record goes up now, and the answer below does not wait for it. A failed upload is handed
  // to the outage queue inside `settle`, so this never rejects; it is only reported.
  if (outcome.auditId) {
    void audit.settle(outcome.auditId).then((settled) => {
      if (!settled.uploaded) console.error(`[ibems-proxy] command record kept on the edge for upload: ${settled.detail}`);
      // RM-159: the scheduler's aircon hold reads people's commands from the database, and no longer
      // re-reads it every minute. Told once the row is there, so its next read finds it.
      else signalConfigChanged('a command');
    });
  }

  // Audit completeness is part of Phase 6's DoD: no record, no command. A refusal here means the
  // edge could not write the record at all — nothing has touched hardware.
  if (outcome.auditFailure) {
    console.error(`[ibems-proxy] command audit record failed: ${outcome.auditFailure}`);
    return sendJson(res, 502, { error: 'audit_log_unreachable', detail: 'Could not record this command — refusing to proceed without an audit trail.' });
  }

  // The attempt is logged above (status:'failed', not silently omitted — an
  // attempted-and-failed command is exactly what a safety-critical audit trail exists to
  // capture) before this refusal, so the record survives even though the caller gets an
  // error rather than the ack.
  if (outcome.dispatchFailure) {
    // One code per failure MODE, not one code for "dispatch failed".
    //
    // Every one of these used to answer `hardware_dispatch_failed`, which the app rendered as
    // "The bridge did not accept the command (502)." So "the bridge reports THIS DEVICE
    // offline" — a fact about one socket, with a remedy at that socket — was indistinguishable
    // from the bridge being down. A physical test on 2026-08-31 reported exactly that
    // misreading as "bridge not reachable", while the bridge was serving readings throughout,
    // and it sent the diagnosis in the wrong direction for a fortnight.
    //
    // `detail` stays generic and names no host, port or upstream body: this response crosses
    // into a browser. The specifics are in the audit row and the journal.
    const FAILURE = {
      device_offline: {
        code: 'device_offline',
        detail: 'The bridge has no connection to this device, so the command could not reach it. The command was logged.',
      },
      bridge_unreachable: {
        code: 'bridge_unreachable',
        detail: 'The bridge could not be reached, so the command was not delivered. The command was logged.',
      },
      bridge_rejected: {
        code: 'bridge_rejected',
        detail: 'The bridge refused the command. The command was logged.',
      },
      no_route: {
        code: 'no_dispatch_route',
        detail: 'This deployment has no way to command a device of this kind. The command was logged.',
      },
      // Distinct from `no_dispatch_route`, and the difference is the remedy. That one means the
      // device cannot be commanded at all; this means SETTINGS have no LAN endpoint yet, so the
      // vendor cloud carries them — and it was not reachable either. An operator reading this
      // should check the internet, not the device.
      no_local_capability_route: {
        code: 'capability_needs_cloud',
        detail: 'Settings are sent through the vendor cloud until the bridge gains a local route for them, and the cloud could not be reached. The command was logged.',
      },
    };
    const mapped = FAILURE[outcome.dispatchReason] ?? {
      code: 'hardware_dispatch_failed',
      detail: 'The command was validated and logged, but the device did not actually respond — refusing to report it as accepted.',
    };
    console.log(`[ibems-proxy] command ${cmd.device_id} ${cmd.action} answered 502 ${mapped.code} in ${Date.now() - startedMs} ms`);
    return sendJson(res, 502, {
      error: mapped.code,
      code: mapped.code,
      detail: mapped.detail,
      // Which paths were tried. `none` means local AND the vendor cloud both failed, which is a
      // different situation from a deployment with no cloud configured at all — and the two
      // read identically without this.
      via: outcome.via ?? null,
    });
  }

  console.log(`[ibems-proxy] command ${cmd.device_id} ${cmd.action} answered ${ACCEPTED_STATUS} ${outcome.status} via ${outcome.via ?? '-'} in ${Date.now() - startedMs} ms`);
  res.writeHead(ACCEPTED_STATUS, { 'Content-Type': 'application/json', ...CORS_HEADERS });
  // `via` rides on the ack so the page can say HOW the command landed. A cloud-recovered
  // command is a success the operator would otherwise read as unremarkable, while it means the
  // device stopped answering locally — the earliest warning this system has that a device is
  // going bad. Null for a dry run, where no path was attempted.
  res.end(JSON.stringify({ ...ack, via: outcome.via ?? null }));
}

/**
 * What the journal hears about requests — RM-148, Stage 6. Every request used to be a line, and a
 * kiosk read is two (an OPTIONS and a GET): about 32,000 lines a day on 2026-09-29, which held the
 * persistent journal's 200 MB cap to five days of history instead of the ninety RM-125 set it up for.
 * Refusals, writes and upgrades are still logged as they happen; authorized reads are counted and
 * summarised once per interval, by path, so the traffic is still visible without drowning the rest.
 */
const LOG_SUMMARY_MS = Number(process.env.PROXY_LOG_SUMMARY_MS) || 10 * 60 * 1000;
const servedReads = new Map();
setInterval(() => {
  if (servedReads.size === 0) return;
  const total = [...servedReads.values()].reduce((a, n) => a + n, 0);
  const span = LOG_SUMMARY_MS >= 60_000 ? `${Math.round(LOG_SUMMARY_MS / 60_000)} min` : `${Math.round(LOG_SUMMARY_MS / 1000)} s`;
  console.log(`[ibems-proxy] served ${total} authorized read(s) in the last ${span}: ${[...servedReads].map(([p, n]) => `${p} ×${n}`).join(', ')}`);
  servedReads.clear();
}, LOG_SUMMARY_MS).unref();

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  const origin = req.headers['origin'] || '-';

  if (req.method === 'OPTIONS') {
    res.writeHead(204, CORS_HEADERS);
    return res.end();
  }
  if (req.method === 'POST' && url.pathname === '/api/local-login') {
    console.log(`[ibems-proxy] POST /api/local-login origin=${origin}`);
    return handleLocalLogin(req, res);
  }

  const token = tokenFromRequest(req, url);
  const authorized = await isAuthorized(token);
  if (authorized && req.method === 'GET') {
    servedReads.set(url.pathname, (servedReads.get(url.pathname) ?? 0) + 1);
  } else {
    console.log(`[ibems-proxy] ${req.method} ${url.pathname} origin=${origin} token=${token ? token.slice(0, 12) + '…' : 'none'} -> ${authorized ? 'OK' : '401'}`);
  }
  if (!authorized) return sendJson(res, 401, { error: 'unauthorized' });

  if (req.method === 'GET' && url.pathname === '/api/tuya/devices') {
    // Always a 200 since 2026-09-17: the vendor cloud is one optional source (see DEVICE_SOURCES), and
    // `sources` says which of the three answered. A lapsed subscription used to take this whole list —
    // and so Add Device — down with it, while the devices and their imported keys were all still there.
    //
    // Which vendor devices already have a node. Read fresh rather than cached at startup: enrolling
    // one changes this, and a wizard showing a device it just added as still available is worse than
    // one extra read on a page nobody opens often.
    let flows = null;
    try {
      const auth = await createAdminClient({ host: '127.0.0.1', port: BRIDGE_PORT, timeoutMs: 10000 });
      ({ flows } = await auth.getFlows(await auth.login()));
    } catch (err) {
      // Reported, not swallowed. This read needs NODE_RED_ADMIN_USER/PASS, which nothing else here
      // does — so it fails independently, and on failure every `claimed` is false, which is
      // indistinguishable from an empty flow. The wizard then offers devices that already have a node
      // as available: a wrong list that looks right. That is exactly what happened when these keys
      // were missing from server/.env, and it stayed invisible because this catch was empty.
      // `claimed_known` lets the page say it does not know.
      console.error(`[ibems-proxy] claimed-set lookup failed, enrolment candidates unfiltered: ${err.message}`);
    }
    try {
      // Orphans are nodes whose device was re-paired under a new id — concluded cautiously, from LAN
      // silence AND a complete list without it; see deviceSources.mjs. Without the flow there are none.
      const listing = await DEVICE_SOURCES.listWithOrphans(flows ?? [], classForNode);
      if (listing.sources.cloud.status === 'unavailable') {
        console.warn(`[ibems-proxy] vendor cloud listing unavailable (${listing.sources.cloud.detail}); serving imported and LAN sources`);
      }
      return sendJson(res, 200, assertNoSecrets({
        devices: toPublicFleet(listing.devices, flows ? claimedNodesFrom(flows) : new Map()),
        claimed_known: flows !== null,
        orphan_nodes: listing.orphan_nodes,
        sources: listing.sources,
      }));
    } catch (err) {
      console.error(`[ibems-proxy] device listing failed: ${err.message}`);
      return sendJson(res, 500, { error: 'device_listing_failed' });
    }
  }
  if (req.method === 'GET' && url.pathname === '/api/credentials') {
    // What has been imported, without the keys: `publicView` carries each key's length only.
    return sendJson(res, 200, assertNoSecrets({ devices: CREDENTIAL_STORE.publicView() }));
  }
  if (req.method === 'POST' && url.pathname === '/api/credentials/import') {
    return handleCredentialImport(req, res);
  }
  if (req.method === 'GET' && url.pathname === '/api/tuya/presence') {
    // FI-015. Joins the cloud's per-device MAC against this host's ARP table, which is the one
    // diagnostic that separates "off the network, someone must drive to the office" from "on
    // the network but no longer discoverable, which is a config change". It existed only as
    // `npm run tuya:macs` — correct, but reachable solely over SSH, and the split it reports
    // moved twice inside an hour on 2026-08-26. A perishable answer that decides whether
    // somebody makes a journey should not require a terminal.
    const client = getTuyaClient();
    if (!client) return sendJson(res, 501, { error: 'tuya_not_configured' });
    try {
      const devices = await client.listDevices();
      const factoryInfos = await client.listFactoryInfos(devices.map((d) => d.id));
      // Unlike /api/tuya/devices this reads the HOST's neighbour table, so it means nothing
      // anywhere but the Pi. `readable` carries that: an empty table would otherwise be joined
      // into "every device is absent", which is the strongest claim available made from the
      // weakest evidence, and on screen would read as the whole fleet having left the network.
      const { readable, neighbours, reason } = readNeighbours();
      if (!readable) console.warn(`[ibems-proxy] /api/tuya/presence has no ARP view: ${reason}`);
      const rows = joinMacPresence({ cloudDevices: devices, factoryInfos, neighbours });
      return sendJson(res, 200, {
        arp_readable: readable,
        devices: toPublicPresence(rows, { arpReadable: readable }),
      });
    } catch (err) {
      // The upstream message can name the data centre and the account; log it, do not echo it.
      console.error(`[ibems-proxy] tuya presence fetch failed: ${err.message}`);
      return sendJson(res, 502, { error: 'tuya_unavailable' });
    }
  }
  if (req.method === 'GET' && url.pathname === '/api/capabilities') {
    // dispatch_classes is what the gate means in practice, not just whether it is open:
    // with the gate closed nothing dispatches, so the list is empty. The frontend uses it to
    // say which controls are live rather than going silent the moment the gate opens.
    // How many commands were recorded locally because Supabase could not be reached. A
    // command accepted into the buffer is not the same fact as one recorded in the audit
    // table, and the operator must not have to guess which they just did — this project's
    // whole posture is that the UI never claims more than it can observe.
    // RM-158: the policy is read with this caller's session; a break-glass one is not a database session.
    void livePolicy.refresh(false, { token: isValidLocalSession(token) ? undefined : token });
    return sendJson(res, 200, {
      hardware_dispatch_enabled: HARDWARE_DISPATCH_ENABLED,
      dispatch_classes: HARDWARE_DISPATCH_ENABLED ? DISPATCH_CLASSES : [],
      audit_buffer_pending: bufferCount(COMMAND_BUFFER_PATH) + bufferCount(SCHEDULER_BUFFER_PATH),
      // The site's declared policy, plus whether a vendor fallback is actually configured on
      // this deployment. Both, because they answer different questions and the page needs the
      // pair to say anything true: `local-first` with no credentials set behaves identically to
      // `local-only` today and is a completely different promise about tomorrow.
      dispatch_policy: DISPATCH_POLICY,
      cloud_fallback_configured: Boolean(CLOUD_DISPATCH?.client),
      // RM-038. The floor the NEXT command will actually be validated against, which is not
      // necessarily the one in the browser's bundle: an operator can change it without a
      // redeploy, and a setpoint selector built from a stale build value would offer a degree
      // that comes back as a 400 — which reads as a bug rather than as a policy.
      // RM-068: this number means the coldest ROOM TARGET now, not the coldest commandable
      // setpoint. Both keys are served for one release so a kiosk still running the pre-rename
      // bundle does not lose its value the moment phase35 lands.
      acu_min_room_target_c: roomTargetFloorC(livePolicy.current()),
      acu_min_setpoint_c: roomTargetFloorC(livePolicy.current()),
      // Where that number came from. A page reporting a floor it got from the build during a
      // database outage should be able to say so rather than presenting it as current.
      policy_source: livePolicy.status().source,
      // The aircon's two paths (2026-09-17). `acu_cloud_route` is whether a state the local IR
      // library cannot express (any mode but its own, any fan, swing) has anywhere to go:
      // ready | unconfigured | unresolved | local-only, or null with no aircon. The second is whether
      // somebody has watched the unit obey the local library since the hub was re-paired.
      acu_cloud_route: await acuCloudRoute(),
      acu_local_ir_verified: SITE.aircon?.local_ir_verified === true,
      // 2026-09-22: the protocol the flow generates frames in (`shared/irTcl112.mjs`), or null when it
      // can send only its captured library. With one, every state is sendable over the LAN.
      acu_local_ir_protocol: SITE.aircon?.ir_protocol ?? null,
    });
  }
  if (req.method === 'GET' && url.pathname === '/api/archive/status') {
    return handleArchiveStatus(res);
  }
  if (req.method === 'GET' && url.pathname === '/api/archive/readings') {
    return handleArchiveReadings(url, res);
  }
  if (req.method === 'GET' && url.pathname === '/api/archive/anomalies') {
    return handleArchiveAnomalies(url, res);
  }
  if (req.method === 'GET' && url.pathname === '/api/archive/trouble') {
    return handleArchiveTrouble(url, res);
  }
  if (req.method === 'GET' && url.pathname === '/api/archive/connectivity') {
    return handleArchiveConnectivity(url, res);
  }
  if (req.method === 'GET' && url.pathname === '/api/archive/buckets') {
    return handleArchiveBuckets(url, res);
  }
  if (req.method === 'POST' && url.pathname === '/api/config/changed') {
    // RM-159: the page saved a setting to Supabase; the scheduler reads it now rather than at its
    // next safety-net refresh. Moves nothing, so not behind HARDWARE_DISPATCH_ENABLED.
    signalConfigChanged('a setting saved in the app');
    return sendJson(res, 200, { ok: true });
  }
  if (req.method === 'POST' && url.pathname === '/api/enroll') {
    // Authenticated like every other route above. Deliberately NOT behind
    // HARDWARE_DISPATCH_ENABLED: that gate governs moving a relay, and enrolling a device
    // moves nothing. Conflating the two would mean a site that has not opened dispatch could
    // never add a device, which is backwards — you enrol before you switch.
    return handleEnroll(req, res, { readJsonBody, sendJson, token, sources: DEVICE_SOURCES });
  }
  if (req.method === 'POST' && url.pathname === '/api/rebind') {
    // Authenticated like enrolment and for the same reason not behind HARDWARE_DISPATCH_ENABLED:
    // it moves nothing. It points an orphaned node at the device that replaced it after a re-pair.
    return handleRebind(req, res, { readJsonBody, sendJson, token, sources: DEVICE_SOURCES });
  }
  if (req.method === 'POST' && url.pathname === '/api/remove') {
    // Same gate reasoning as enrolment, and the same authentication. Unlike enrolment this
    // needs no vendor cloud — removal reads the flow and the registry only, so it stays
    // available on a deployment with no Tuya credentials, which is also the deployment most
    // likely to need to undo something.
    return handleRemove(req, res, { readJsonBody, sendJson, token });
  }
  if (req.method === 'POST' && url.pathname === '/api/command') {
    return handleCommand(req, res, token);
  }

  proxyHttp(req, res, url);
});

// WebSocket relay: raw TCP, not a WS library — we never parse frames, just authenticate
// the handshake then pipe bytes both directions. Node-RED does the actual WS protocol
// work on the other end; this process only ever forwards.
server.on('upgrade', async (req, clientSocket, head) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  const token = tokenFromRequest(req, url);
  const authorized = await isAuthorized(token);
  console.log(`[ibems-proxy] WS upgrade ${url.pathname} origin=${req.headers['origin'] || '-'} token=${token ? token.slice(0, 12) + '…' : 'none'} -> ${authorized ? 'OK' : '401'}`);
  if (!authorized) {
    clientSocket.write('HTTP/1.1 401 Unauthorized\r\n\r\n');
    clientSocket.destroy();
    return;
  }

  const bridgeSocket = net.connect(BRIDGE_PORT, BRIDGE_HOST, () => {
    const upstream = new URL(url);
    upstream.searchParams.delete('token');
    const lines = [`GET ${upstream.pathname}${upstream.search} HTTP/1.1`];
    for (const [key, value] of Object.entries(req.headers)) {
      if (key.toLowerCase() === 'host') continue;
      lines.push(`${key}: ${value}`);
    }
    lines.push(`Host: ${BRIDGE_HOST}:${BRIDGE_PORT}`, '', '');
    bridgeSocket.write(lines.join('\r\n'));
    if (head?.length) bridgeSocket.write(head);
    bridgeSocket.pipe(clientSocket);
    clientSocket.pipe(bridgeSocket);
  });
  bridgeSocket.on('error', () => clientSocket.destroy());
  clientSocket.on('error', () => bridgeSocket.destroy());
});

server.listen(PROXY_PORT, () => {
  console.log(`[ibems-proxy] listening on :${PROXY_PORT}, forwarding authorized requests to ${BRIDGE_HOST}:${BRIDGE_PORT}`);
});

/**
 * Keep the offline verification keys current. Best-effort by design: a failure here is
 * ordinary (it is exactly what an outage looks like) and must never stop the proxy serving.
 * The keys already on disk stay valid, which is the entire point of persisting them.
 */
if (jwks) {
  const refreshJwks = async () => {
    const res = await jwks.refresh();
    if (res.ok) console.log(`[ibems-proxy] offline session keys refreshed (${res.count})`);
    else console.warn(`[ibems-proxy] could not refresh offline session keys (${res.detail}); using ${res.count} cached`);
  };
  refreshJwks();
  // unref: this timer must not hold the process open at shutdown.
  setInterval(refreshJwks, JWKS_REFRESH_MS).unref();
}

for (const sig of ['SIGTERM', 'SIGINT']) {
  process.on(sig, () => {
    console.log(`[ibems-proxy] received ${sig}, shutting down`);
    // server.close() alone stops accepting NEW connections but waits indefinitely for
    // existing ones to end on their own — a live WS relay (see the 'upgrade' handler
    // above) never closes by itself, so a browser with the dashboard open would leave
    // this hanging until systemd's stop timeout expired and SIGKILLed it (~90s of the
    // proxy being unreachable on every single restart — confirmed the hard way, see the
    // architecture plan's Phase 5 incident notes). closeAllConnections() forcibly ends
    // every socket the http.Server itself tracks, but measured ~27s to actually exit
    // with a real WS held open — an upgraded connection's *relayed* outbound leg (the
    // separate `net.connect()` to the bridge in the 'upgrade' handler) isn't one of
    // those tracked sockets, so something was still lingering. A hard timeout below
    // guarantees a prompt exit regardless of what closeAllConnections() does or doesn't
    // reach — don't trust the graceful path alone a second time without re-verifying.
    server.close(() => process.exit(0));
    server.closeAllConnections();
    setTimeout(() => process.exit(0), 2000);
  });
}
