/**
 * Monthly report generation — architecture plan Phase 12.
 *
 * WHAT THIS IS FOR:
 * a stored, downloadable record of what the building consumed each month, for someone who
 * will never open the dashboard. The aggregation itself lives in Postgres
 * (`generate_monthly_report`, supabase/phase12_monthly_reports.sql) so a month of rows never
 * crosses the Pi's uplink to be summed; this module only decides WHICH months still need one.
 *
 * WHY THE TRIGGER IS STATELESS:
 * exactly the reasoning server/retention.mjs's header sets out, and deliberately the same
 * shape. There is no last-run file and no cron. Each pass asks the database a question it can
 * always answer — "which settled months have no report, or one built before they settled?" —
 * and acts on the answer. A restart can neither double-run (the month now has a report dated
 * after its settle point) nor skip (the next pass asks again).
 *
 * WHY A GRACE PERIOD:
 * a month is not finished being written the instant it ends. `ingestBuffer.mjs` flushes rows
 * buffered during an outage whenever Supabase comes back, and the hourly rollup runs every
 * six hours. Reporting a month at 00:01 on the 1st can therefore miss its own last hours, and
 * a report that quietly undercounts is worse than one that arrives two days later.
 *
 * WHY A REPORT CAN BE REGENERATED, AND EXACTLY ONCE:
 * "months with no report row" was not quite the right question. A report generated by hand
 * for a month still in progress would satisfy it forever, freezing that month at partial
 * data — even though `generate_monthly_report` upserts and a rebuild would see more. The
 * question this asks instead is "months with no report row, or whose report was built before
 * the month had finished settling". That is self-limiting: the daemon only ever generates at
 * or after the settle point, so its own reports are never rebuilt, and a too-early one is
 * rebuilt exactly once.
 */

/** Days to wait after a month ends before reporting it. See the header. */
export const REPORT_GRACE_DAYS = 2;

/** Most months one pass will generate. A first run against years of history should not hold
 * the daemon in one long loop — and it does not need to, because nothing is remembered
 * between passes and the next one resumes exactly where this stopped. */
export const MAX_MONTHS_PER_PASS = 6;

/** Most weeks one pass will generate — RM-041. Higher than the month cap because weeks accrue
 * about 4.3x faster, so a first run against a year of history would otherwise take a dozen
 * passes to catch up. Same self-limiting reasoning either way: nothing is remembered between
 * passes and the next one resumes where this stopped. */
export const MAX_WEEKS_PER_PASS = 12;

/** `YYYY-MM-DD` of the Monday on or before a UTC instant. `getUTCDay()` is 0 for Sunday, so
 * Sunday steps back six days rather than one — the off-by-one that makes a week start on the
 * wrong day is exactly this expression. */
function weekKey(date) {
  const d = new Date(date.getTime());
  const back = (d.getUTCDay() + 6) % 7;
  d.setUTCDate(d.getUTCDate() - back);
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-${String(d.getUTCDate()).padStart(2, '0')}`;
}

/**
 * Pure. Which weeks still need a report? — RM-041.
 *
 * The same shape and the same reasoning as `monthsNeedingReport`, including the grace period and
 * the rebuild-once rule; only the step differs. The UTC-versus-local caveat in that function's
 * header applies here identically and for the same reason: Manila is UTC+8, so a local week ends
 * before the UTC boundary and waiting for the UTC one can only be conservative.
 *
 * @param {{ generatedWeeks: Array<string|{period_start: string, generated_at?: string}>,
 *           earliestDataTs: string|null, nowMs: number, graceDays?: number }} args
 * @returns {string[]} `YYYY-MM-DD` Mondays, oldest first, at most MAX_WEEKS_PER_PASS of them.
 */
export function weeksNeedingReport({ generatedWeeks, earliestDataTs, nowMs, graceDays = REPORT_GRACE_DAYS }) {
  if (earliestDataTs === null || earliestDataTs === undefined) return [];
  const earliestMs = Date.parse(earliestDataTs);
  if (Number.isNaN(earliestMs)) return [];

  const generatedAt = new Map();
  for (const w of generatedWeeks ?? []) {
    const key = String(typeof w === 'string' ? w : (w?.period_start ?? '')).slice(0, 10);
    if (key) generatedAt.set(key, typeof w === 'string' ? null : (w?.generated_at ?? null));
  }

  const weeks = [];
  let cursor = Date.parse(`${weekKey(new Date(earliestMs))}T00:00:00Z`);
  while (weeks.length < MAX_WEEKS_PER_PASS) {
    const nextWeek = cursor + 7 * DAY_MS;
    const settledAt = nextWeek + graceDays * DAY_MS;
    if (settledAt > nowMs) break;

    const key = weekKey(new Date(cursor));
    if (!generatedAt.has(key)) {
      weeks.push(key);
    } else {
      const at = Date.parse(generatedAt.get(key) ?? '');
      if (!Number.isFinite(at) || at < settledAt) weeks.push(key);
    }
    cursor = nextWeek;
  }
  return weeks;
}

/** How often to look for missing reports. The answer changes at most once a month; this is
 * frequent enough to pick one up the same day and cheap enough to be irrelevant. */
export const REPORT_CHECK_MS = 6 * 60 * 60 * 1000; // 6h

const DAY_MS = 24 * 60 * 60 * 1000;

/** `YYYY-MM-01` for the month containing a UTC instant. */
function monthKey(date) {
  return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, '0')}-01`;
}

/**
 * Pure. Which months still need a report?
 *
 * Month boundaries are computed in UTC while the report itself groups days in the site's
 * timezone (`p_tz`, default Asia/Manila). That mismatch is deliberate and safe in one
 * direction only: Manila is UTC+8, so a local month ends BEFORE the UTC month boundary, and
 * waiting for the UTC boundary plus a grace period can only ever be conservative. A site west
 * of UTC would need this revisited — hence saying so here rather than leaving it implied.
 *
 * @param {{ generatedMonths: Array<string|{month: string, generated_at?: string}>,
 *           earliestDataTs: string|null, nowMs: number, graceDays?: number }} args
 * @returns {string[]} `YYYY-MM-01` keys, oldest first, at most MAX_MONTHS_PER_PASS of them.
 */
export function monthsNeedingReport({ generatedMonths, earliestDataTs, nowMs, graceDays = REPORT_GRACE_DAYS }) {
  if (earliestDataTs === null || earliestDataTs === undefined) return [];
  const earliestMs = Date.parse(earliestDataTs);
  // An unparseable timestamp is a reason to do nothing and say so, not a reason to guess —
  // the same resolution shouldRunRetention takes for the same ambiguity.
  if (Number.isNaN(earliestMs)) return [];

  // A `date` column can arrive as '2026-05-01' or as a full timestamp depending on how the
  // client rendered it. Normalising to the first 10 characters makes both the same month;
  // not doing so would regenerate every report on every pass.
  const generatedAt = new Map();
  for (const m of generatedMonths ?? []) {
    const key = String(typeof m === 'string' ? m : (m?.month ?? '')).slice(0, 10);
    if (key) generatedAt.set(key, typeof m === 'string' ? null : (m?.generated_at ?? null));
  }

  const months = [];
  const cursor = new Date(Date.UTC(new Date(earliestMs).getUTCFullYear(), new Date(earliestMs).getUTCMonth(), 1));
  while (months.length < MAX_MONTHS_PER_PASS) {
    const nextMonth = Date.UTC(cursor.getUTCFullYear(), cursor.getUTCMonth() + 1, 1);
    // The moment this month is both over and given time for late-flushing rows to land.
    const settledAt = nextMonth + graceDays * DAY_MS;
    // Not settled yet — and since months only get newer from here, neither is anything after.
    if (settledAt > nowMs) break;

    const key = monthKey(cursor);
    if (!generatedAt.has(key)) {
      months.push(key);
    } else {
      const at = Date.parse(generatedAt.get(key) ?? '');
      // A report built before its month settled saw an incomplete month. Rebuild it once.
      // An unparseable or absent timestamp counts as stale: ambiguity resolves toward
      // regenerating, which is idempotent and cheap, rather than toward leaving a wrong
      // number in place. That is the opposite direction from shouldRunRetention, whose only
      // destructive branch is a DELETE — there, ambiguity has to resolve to "do nothing".
      if (!Number.isFinite(at) || at < settledAt) months.push(key);
    }
    cursor.setUTCMonth(cursor.getUTCMonth() + 1);
  }
  return months;
}

/** The `ts`/`hour` of the oldest row in a table, or null when it is empty. */
async function oldestStamp(client, table, column) {
  const rows = await client.select(table, `select=${column}&order=${column}.asc&limit=1`);
  return Array.isArray(rows) && rows.length > 0 ? rows[0][column] : null;
}

/**
 * Generates every missing report, oldest month first.
 *
 * One month failing does not abandon the rest: a report is per-month and independent, so a
 * single bad month should not cost the good ones — the same reasoning `useAnalyticsHistory`'s
 * `Promise.allSettled` follows for per-device fetches. Failures are returned rather than
 * thrown so the caller can log them and carry on.
 *
 * @param {{ client: {select: Function, rpc: Function}, nowMs?: number, tz?: string }} args
 * @returns {Promise<{ generated: string[], failed: Array<{month: string, error: string}>,
 *                     reason: string }>} `reason` is set only when nothing was generated.
 */
export async function runReportGeneration({ client, nowMs = Date.now(), tz }) {
  // The archive is consulted as well as the raw table, and the EARLIER of the two wins.
  // `readings` is pruned at 30 days, so its oldest row is newer than the archive's — trusting
  // it alone would silently skip every month that had already been rolled up.
  const [oldestHour, oldestRaw] = await Promise.all([
    oldestStamp(client, 'readings_hourly', 'hour'),
    oldestStamp(client, 'readings', 'ts'),
  ]);
  const candidates = [oldestHour, oldestRaw].filter((t) => t !== null && !Number.isNaN(Date.parse(t)));
  const earliestDataTs = candidates.length > 0 ? candidates.reduce((a, b) => (Date.parse(a) <= Date.parse(b) ? a : b)) : null;

  // ASKED OF `period_building_reports`, NOT `monthly_building_reports` — RM-041. That is the
  // table the Reports page reads, so it is the one whose gaps matter. Asking the old table would
  // report a month as done while the page still showed nothing for it.
  //
  // `generated_at`, not just the date: staleness cannot be judged without it.
  const generatedRows = await client.select(
    'period_building_reports',
    'select=period_start,generated_at&period=eq.month&order=period_start.asc&limit=1000'
  );
  const generatedMonths = (generatedRows ?? []).map((r) => ({ month: r.period_start, generated_at: r.generated_at }));
  const missing = monthsNeedingReport({ generatedMonths, earliestDataTs, nowMs });

  const generatedWeekRows = await client.select(
    'period_building_reports',
    'select=period_start,generated_at&period=eq.week&order=period_start.asc&limit=1000'
  );
  const missingWeeks = weeksNeedingReport({ generatedWeeks: generatedWeekRows, earliestDataTs, nowMs });

  // Said precisely, because "nothing to do" covers three different situations and the log
  // line used to claim the most reassuring one. "Every complete month already has one" is
  // vacuously true when no month has finished at all, and reads to whoever is scanning the
  // journal as though reports exist.
  let reason = '';
  if (earliestDataTs === null) {
    reason = 'no readings yet';
  } else if (missing.length === 0 && missingWeeks.length === 0) {
    reason = (generatedMonths ?? []).length > 0
      ? 'every settled month and week already has a current report'
      : 'no period has finished settling yet';
  }

  const generated = [];
  const generatedWeeks = [];
  const failed = [];
  for (const month of missing) {
    try {
      await client.rpc('generate_period_report', tz ? { p_period: 'month', p_start: month, p_tz: tz } : { p_period: 'month', p_start: month });
      // ALSO the phase12 function, on purpose and temporarily. Its tables are no longer read by
      // the app, but keeping them current is what makes the two comparable — the check that the
      // generalised aggregation still agrees with the one it replaced. RM-042 retires them, and
      // this call goes with them.
      await client.rpc('generate_monthly_report', tz ? { p_month: month, p_tz: tz } : { p_month: month });
      generated.push(month);
    } catch (err) {
      failed.push({ month, error: String(err) });
    }
  }
  for (const week of missingWeeks) {
    try {
      await client.rpc('generate_period_report', tz ? { p_period: 'week', p_start: week, p_tz: tz } : { p_period: 'week', p_start: week });
      generatedWeeks.push(week);
    } catch (err) {
      // Keyed `month` like the monthly failures, because the caller logs one list. A week's key
      // is a full date and a month's is a first-of-month, so the two are never ambiguous.
      failed.push({ month: week, error: String(err) });
    }
  }
  return { generated, generatedWeeks, failed, reason };
}
