#!/usr/bin/env node
/**
 * `npm run site:sql` — the `sites` row for this deployment, as a statement to paste. RM-033.
 *
 * WHY THIS EXISTS. `supabase/phase19_sites.sql` seeds one id: this building's. A second
 * institution therefore had to **hand-edit a migration** to insert its own — and editing a
 * migration that has already run somewhere is precisely how two databases stop agreeing about
 * what has been applied. `docs/replication.md` listed it as an open gap for exactly that reason.
 * The row is a fact about a deployment, not a schema change, so it belongs in a generated
 * statement rather than in the migration history.
 *
 * IT PRINTS. IT DOES NOT EXECUTE. Writing to a production database unattended is not something a
 * scaffolding command should do — the same line `scripts/install.sh`, `site-new.mjs` and
 * `preflight.mjs` all hold. `npm run preflight` tells you whether the row is there; this gives
 * you the statement that puts it there; a person runs it.
 *
 * The generated statement is idempotent, because someone unsure whether they ran it will run it
 * again, and that must not be a destructive act. It updates the mutable fields on conflict and
 * never reassigns the id.
 */

/** The same rule `site-new.mjs` and `site-check.mjs` apply — and here the id is also SQL. */
const SLUG = /^[a-z0-9]+(-[a-z0-9]+)*$/;

/** PostgreSQL string literal. Doubling the quote is the whole escape; there is no backslash
 * escaping in a standard-conforming string. "St John's Annex" is an ordinary building name. */
const lit = (value) => `'${String(value).replace(/'/g, "''")}'`;

/**
 * @param {{id: string, display_name: string, timezone: string, utc_offset_minutes: number, policy?: object}} site
 * @returns {string} one `insert ... on conflict do update` statement.
 *
 * Throws rather than emitting a statement it cannot vouch for. SQL with `undefined` interpolated
 * into it does not fail — it runs, and writes nonsense into the table every other table
 * references.
 */
export function siteSeedSql(site) {
  const s = site ?? {};
  if (typeof s.id !== 'string' || !SLUG.test(s.id)) {
    // Deliberately no example slug here. `test/site-config.test.mjs` fails any module outside
    // `shared/siteConfig.mjs` that names a site directory, and it cannot tell a usage string from
    // a wiring mistake — which is the point, since neither can a reader. `site-new.mjs` was
    // caught by the same guard for the same reason.
    throw new Error(`site id must be a lower-case slug of letters, digits and hyphens — got ${JSON.stringify(s.id)}`);
  }
  if (typeof s.display_name !== 'string' || !s.display_name.trim()) {
    throw new Error('site display_name is required');
  }
  if (typeof s.timezone !== 'string' || !s.timezone.trim()) {
    throw new Error('site timezone is required — an IANA zone, e.g. "Asia/Manila"');
  }
  if (!Number.isInteger(s.utc_offset_minutes)) {
    throw new Error('site utc_offset_minutes must be a whole number of minutes east of UTC');
  }

  // `policy` is `not null default '{}'`, and a site with no operating rules yet is a legitimate
  // state — it is what `site:new` scaffolds on purpose. Null would be rejected by the column.
  const policy = JSON.stringify(s.policy ?? {});

  return [
    `-- The sites row for ${s.id}. Generated by \`npm run site:sql\` from`,
    `-- shared/sites/${s.id}/site.mjs — do not hand-edit a migration to change it.`,
    '-- Safe to run more than once.',
    'insert into sites (id, display_name, timezone, utc_offset_minutes, policy)',
    'values (',
    `  ${lit(s.id)},`,
    `  ${lit(s.display_name)},`,
    `  ${lit(s.timezone)},`,
    `  ${s.utc_offset_minutes},`,
    `  ${lit(policy)}::jsonb`,
    ')',
    'on conflict (id) do update set',
    '  display_name       = excluded.display_name,',
    '  timezone           = excluded.timezone,',
    '  utc_offset_minutes = excluded.utc_offset_minutes,',
    '  policy             = excluded.policy;',
    '',
  ].join('\n');
}

// --- CLI ---------------------------------------------------------------------
if (process.argv[1] && process.argv[1].endsWith('site-sql.mjs')) {
  const { SITE } = await import('../shared/siteConfig.mjs');
  process.stdout.write(siteSeedSql(SITE));
  process.stderr.write(
    '\nNothing was executed. Paste the statement above into the SQL editor for this project,\n' +
      'then re-run `npm run preflight` to confirm the row is there.\n',
  );
}
