/**
 * The Aircon tab's function-node sources, as one module both writers import.
 *
 * Two scripts put these nodes on the live flow: `aircon-flow.mjs` refactors the tab that already
 * exists, and `add-device-endpoints.mjs` builds the `/acu` endpoint on a flow that has none. If each
 * carried its own copy, a fresh install and a refactored one would disagree about what the
 * endpoint accepts — which is exactly the kind of drift nothing notices until a command is refused.
 *
 * WHAT CHANGED ON 2026-09-17, AND WHY THE TAB NEEDED IT. The IR blaster was re-paired as a Lasco
 * "Smart IR" hub. Its own dps are two room sensors (101 temp_current, 102 humidity_value) and an
 * IR send/learn pair (201, 202); the aircon's state lives on a virtual "Air" remote in the vendor
 * cloud. The tab it joined had been written for a blaster that never connected, and three of its
 * assumptions would have been wrong the moment this one did:
 *
 *   - `ACU auth + validate` answered 200 in PARALLEL with `AC Master Logic`, so a disconnected hub
 *     or a state the library has no code for still reported success, and the cloud fallback in
 *     `server/dispatchLight.mjs` could never fire. The reply now comes from AC Master Logic itself,
 *     after it knows whether a code was sent.
 *   - Nothing recorded what was commanded, so the app could show a setpoint but not a mode, a fan or
 *     when. `ac_command` now writes the full commanded state, from either path.
 *   - The sensor parser stamped nothing and knew nothing of the session, so `buildLatest` could
 *     neither age the reading nor tell a dead hub from a quiet one.
 *
 * Every source here is ES5-plus-arrow JavaScript as a Node-RED function node runs it: no imports,
 * `msg`, `flow`, `context` and `env` in scope. The constants they need are inlined as JSON literals
 * from `shared/`, so the flow cannot disagree with the contract it implements.
 */

import { AC_MODES, AC_FANS, AC_SETPOINT_MIN_C, AC_SETPOINT_MAX_C, LOCAL_LIBRARY_STATE } from '../shared/acState.mjs';
import { CAPABILITY_PROFILES, divisorFor } from '../shared/deviceCapabilities.mjs';
import { tcl112Code } from '../shared/irTcl112.mjs';

/** How often the IR hub is asked for its dps. `STALE_AFTER_MS_BY_CLASS.acu_ir` is held above it. */
export const HUB_POLL_INTERVAL_S = 60;

/** Marks generated source, so a human about to edit one in the Node-RED editor is warned first. */
export const AIRCON_MARKER = 'GENERATED by node-red-bridge/airconFlowPlan.mjs';

/** The `ac_dash_state` keys `shared/buildLatest.mjs` reads. The state manager must write every one. */
export const AC_DASH_STATE_KEYS = Object.freeze([
  'power', 'setTemp', 'roomTemp', 'humidity', 'outTemp',
  'hubHealth', 'sensedAt', 'mode', 'fan', 'swing', 'commandedAt', 'commandVia',
]);

const json = (v) => JSON.stringify(v);

const header = (what) => `// ${AIRCON_MARKER} — ${what}.
// Do not hand-edit: regenerate with \`npm run aircon:pi\`. Editing here puts this node back outside
// anything in the repository that can verify it.
`;

/**
 * The hub's sensor parser, generated from the `wnykq_ir_hub` catalogue entry.
 *
 * Output 1 carries the hub's session health and, when a sensor arrived, its values and the moment
 * they were sensed. Output 2 carries a learned IR code (dp 202) when one arrives. Both are wired to
 * the Dashboard State Manager, as the two outputs of the hand-written parser it replaces were.
 *
 * Plausibility bounds are the vendor's declared ranges, converted: a value outside them is dropped
 * rather than clamped, because a clamped reading is a fabricated one.
 */
export function hubParserSource(profile = CAPABILITY_PROFILES.wnykq_ir_hub) {
  const sensors = {};
  for (const c of profile.capabilities) {
    if (c.kind !== 'value') continue;
    const div = divisorFor(c);
    sensors[c.dp] = [c.code, div, c.min / div, c.max / div];
  }
  const learned = profile.capabilities.find((c) => c.code === 'ir_study_code');
  return `${header(`IR hub parser, from shared/deviceCapabilities.mjs (${profile.id})`)}
const p = msg.payload;
const dps = p && typeof p === 'object' ? ((p.data && p.data.dps) || p.dps || null) : null;

// Session health. The tuya node reports CONNECTED / DISCONNECTED / ERROR, bare or under \`.state\`;
// dps arriving at all proves the session is alive.
let health = flow.get("acu_hub_health") === true;
if (p === "CONNECTED" || (p && p.state === "CONNECTED")) health = true;
else if (p === "DISCONNECTED" || p === "ERROR" || (p && (p.state === "DISCONNECTED" || p.state === "ERROR"))) health = false;
else if (dps) health = true;
flow.set("acu_hub_health", health);

// dp -> [code, divisor, min, max], in canonical units.
const SENSORS = ${json(sensors)};
const out = { health: health };
let learned = null;
if (dps) {
    for (const k in SENSORS) {
        const raw = dps[k];
        if (raw === undefined || raw === null) continue;
        const n = Number(raw);
        if (!isFinite(n)) continue;
        const s = SENSORS[k];
        const v = Math.round((n / s[1]) * 10) / 10;
        if (v < s[2] || v > s[3]) continue;
        out[s[0]] = v;
    }
    if (out.temp_current !== undefined || out.humidity_value !== undefined) out.sensedAt = Date.now();
    const code = dps["${learned ? learned.dp : 202}"];
    if (code !== undefined && code !== null && code !== "") learned = { code: String(code), at: Date.now() };
}
return [{ topic: "acu_hub", payload: out }, learned ? { topic: "acu_ir_learned", payload: learned } : null];
`;
}

/**
 * The Dashboard State Manager: the one writer of `ac_dash_state`.
 *
 * The `Breaker_Ambient_Temp -> outTemp` branch is the uninstalled Outside Temp sensor's path and is
 * kept exactly as it was, as is the inert ESP32 branch (its node is disabled). Everything else is
 * new, and every commanded field is written only when present, so an OFF command keeps the last
 * setpoint on record.
 */
export const STATE_MANAGER_SOURCE = `${header('the one writer of ac_dash_state')}
const state = flow.get("ac_dash_state") || {
    power: "OFFLINE",
    setTemp: "--",
    roomTemp: "--",
    humidity: "--",
    outTemp: "--"
};
const p = msg.payload;

if (msg.topic === "acu_hub" && p) {
    // Measured, by the hub's own sensors.
    state.hubHealth = p.health === true;
    if (p.temp_current !== undefined) state.roomTemp = p.temp_current;
    if (p.humidity_value !== undefined) state.humidity = p.humidity_value;
    if (p.sensedAt) state.sensedAt = p.sensedAt;
} else if (msg.topic === "ac_command" && p) {
    // COMMANDED, not measured: an IR aircon has no readback. buildLatest serves these as such.
    state.power = p.power === true;
    if (p.setpoint_c !== undefined) state.setTemp = p.setpoint_c;
    if (p.mode !== undefined) state.mode = p.mode;
    if (p.fan !== undefined) state.fan = p.fan;
    if (p.swing !== undefined) state.swing = p.swing;
    state.commandedAt = p.at;
    state.commandVia = p.via;
} else if (msg.topic === "acu_ir_learned" && p) {
    // The code itself stays in this node's context: it is a raw IR payload, not a reading.
    state.lastLearnedAt = p.at;
    context.set("last_learned", p);
} else if (msg.topic === "nbric/ac/status") {
    // Legacy ESP32 sniffer path. Its node is disabled; kept so re-enabling it changes nothing here.
    if (p && p.power) state.power = p.power;
    if (p && p.temp) state.setTemp = p.temp;
} else if (msg.topic === "Breaker_Ambient_Temp") {
    // Outside Temp (not installed) — unchanged.
    state.outTemp = p;
}

flow.set("ac_dash_state", state);
return { payload: state };
`;

/**
 * AC Master Logic: the only node that sends an IR code to the hub.
 *
 * `head` and `library` are the live node's own — extracted from it by `extractIrLibrary`, never
 * retyped — so regenerating this node cannot change a single code.
 *
 * Three outputs: the IR set for the hub, the commanded state for the State Manager, and the HTTP
 * reply. The reply is emitted only when the message came through `/acu` (`msg.res`), and it says
 * what actually happened:
 *
 *   200 sent      a code went to a connected hub — `source` says whether it was a captured frame or
 *                 one generated from the site's declared IR protocol (`SITE.aircon.ir_protocol`)
 *   200 recorded  the proxy is recording a state the vendor cloud carried (`record_only`)
 *   422           no_local_code — neither the library nor the protocol can express this state; the
 *                 proxy tries the cloud
 *   409           device_offline — the hub session is down, so a local send would vanish
 *   400           invalid_state
 */
export function acMasterLogicSource({ head, library, libraryState = LOCAL_LIBRARY_STATE, protocol = null }) {
  if (protocol !== null && protocol !== 'tcl112') throw new Error(`unsupported IR protocol "${protocol}" — only tcl112 can be generated`);
  // A captured ON frame to build the others on. Which one does not matter — every captured ON code is
  // reproduced exactly from any other (test/ir-tcl112.test.mjs) — so prefer a middling setpoint.
  const onKeys = Object.keys(library).filter((k) => /^[0-9]+$/.test(k));
  const templateKey = onKeys.includes('24') ? '24' : onKeys[0];
  const generator = protocol === 'tcl112' && templateKey
    ? `
// GENERATED FRAMES (2026-09-22). The captured library decodes as TCL112AC, so any state the remote
// can express is built on one captured ON frame — shared/irTcl112.mjs, inlined because a function node
// cannot import. OFF and the captured states are always sent exactly as captured.
const TEMPLATE = library[${json(templateKey)}];
const tcl112Code = ${tcl112Code.toString()};
`
    : `
const tcl112Code = null; // no protocol declared for this site's aircon: the captured library only
`;
  return `${header('AC Master Logic, the only sender of IR codes')}
const head = ${json(head)};
const library = ${JSON.stringify(library, null, 4)};
// What the library encodes besides the setpoint — shared/acState.mjs LOCAL_LIBRARY_STATE.
const LIB = ${json(libraryState)};
${generator}
const reply = (code, body) => (msg.res ? Object.assign({}, msg, { statusCode: code, payload: body }) : null);

let s = msg.payload;
// The legacy bare key ("OFF", "16".."30") still works, as the library's own state.
if (typeof s === "string") {
    s = s === "OFF" ? { power: "off" } : { power: "on", mode: LIB.mode, setpoint_c: Number(s), fan: LIB.fan, swing: LIB.swing };
}
if (!s || (s.power !== "on" && s.power !== "off")) return [null, null, reply(400, { ok: false, error: "invalid_state" })];

const now = Date.now();
const record = (via) => ({
    topic: "ac_command",
    payload: { power: s.power === "on", setpoint_c: s.setpoint_c, mode: s.mode, fan: s.fan, swing: s.swing, at: now, via: via }
});

if (s.record_only === true) return [null, record("cloud"), reply(200, { ok: true, recorded: true })];

let key = null;
if (s.power === "off") key = "OFF";
else if (s.mode === LIB.mode && s.fan === LIB.fan && s.swing === LIB.swing) key = String(s.setpoint_c);
let code = key === null ? undefined : library[key];
let source = "captured";
if (code === undefined && s.power === "on" && tcl112Code) {
    code = tcl112Code(TEMPLATE, s) || undefined;
    source = "generated";
}
if (code === undefined) return [null, null, reply(422, { ok: false, error: "no_local_code" })];
if (flow.get("acu_hub_health") !== true) return [null, null, reply(409, { ok: false, error: "device_offline" })];

const ir = { payload: { dps: 201, set: JSON.stringify({ control: "send_ir", head: head, key1: code, type: 0, delay: 300 }) } };
return [ir, record("local"), reply(200, { ok: true, sent: "local", key: key, source: source })];
`;
}

/**
 * The `/acu` endpoint's auth and validation.
 *
 * Accepts the full state `{state: {power, mode, setpoint_c, fan, swing}, record_only?}` and, for one
 * release, the legacy `{mode: "OFF" | "16".."30"}`. Validated against the same vocabulary
 * `shared/commands.mjs` enforces, because this arrives from the network.
 *
 * `[0-9]` rather than a backslash class: this source lives in a template literal, and a lost
 * backslash would silently change the pattern.
 */
export const ACU_AUTH_FN = `const TOKEN = env.get('LIGHT_API_TOKEN');
if (!TOKEN || msg.req.headers['x-auth-token'] !== TOKEN) {
    msg.statusCode = 401;
    msg.payload = { ok:false, error:'unauthorized' };
    return [null, msg];
}
const MODES = ${json(AC_MODES)};
const FANS = ${json(AC_FANS)};
const MIN_C = ${AC_SETPOINT_MIN_C}, MAX_C = ${AC_SETPOINT_MAX_C};
const b = msg.payload || {};
let s = null;
if (b.state && typeof b.state === 'object') {
    const t = b.state;
    const onOk = t.power === 'on' && MODES.indexOf(t.mode) >= 0 && FANS.indexOf(t.fan) >= 0 &&
        typeof t.swing === 'boolean' && Number.isInteger(t.setpoint_c) && t.setpoint_c >= MIN_C && t.setpoint_c <= MAX_C;
    if (t.power === 'off' || onOk) {
        s = { power: t.power, mode: t.mode, setpoint_c: t.setpoint_c, fan: t.fan, swing: t.swing, record_only: b.record_only === true };
    }
} else {
    // Legacy body, kept for one release: the OFF code or a whole degree 16-30 in the library's state.
    const mode = String(b.mode || '');
    if (mode === 'OFF' || (/^[0-9]{2}$/.test(mode) && Number(mode) >= MIN_C && Number(mode) <= MAX_C)) s = mode;
}
if (s === null) {
    msg.statusCode = 400;
    msg.payload = { ok:false, error:'state must be {power:"off"} or a full on-state (mode, setpoint_c 16-30, fan, swing)' };
    return [null, msg];
}
msg.payload = s;
delete msg.loop_prevention;
return [msg, null];`;

/** The hub poll: a GET every HUB_POLL_INTERVAL_S, skipped while the session is known to be down. */
export const HUB_POLL_GATE_SOURCE = `${header('IR hub poll gate')}
// A known-dead session gets no traffic; an unknown one (just started) does.
return flow.get("acu_hub_health") === false ? null : { payload: { operation: "GET" } };
`;

/**
 * `head` and `library` out of an AC Master Logic source — the legacy hand-written node or a
 * generated one, which spell them the same way. Returns null rather than guessing if either is
 * missing or unparseable: regenerating the node must never lose or alter a code.
 */
export function extractIrLibrary(func) {
  const src = String(func ?? '');
  const headMatch = /const head = "([0-9a-fA-F]+)";/.exec(src);
  const libMatch = /const library = (\{[\s\S]*?\});/.exec(src);
  if (!headMatch || !libMatch) return null;
  try {
    const library = JSON.parse(libMatch[1]);
    const values = Object.values(library);
    if (!values.length || values.some((v) => typeof v !== 'string' || !v)) return null;
    return { head: headMatch[1], library };
  } catch {
    return null;
  }
}
