/**
 * FI-022 — a LOCAL route for capability writes, planned rather than hand-built.
 *
 * WHAT WAS MISSING. `server/dispatchLight.mjs`'s `hasLocalCapabilityRoute()` returned `false`,
 * so every capability write — a power-alarm threshold, a countdown, a child lock — went to the
 * vendor cloud even though the device sits on the Pi's own 2.4 GHz segment. The site declares
 * `dispatch: 'local-first'`; that was true of relays and untrue of settings.
 *
 * WHY IT COULD NOT JUST REUSE THE RELAY ROUTE. Traced on the live flow 2026-09-08: the light
 * chain is hard-wired to a boolean. `Auth + validate` coerces the payload with
 * `s = Boolean(s)`, `Lights Router` keys on `topic: 'L1'..'L7'`, and each `Format CMD` node is
 * literally `msg.payload = {dps: 1, set: msg.payload}`. Every stage assumes a relay, so carrying
 * a dp through would mean rewriting four stages of a hand-built control path.
 *
 * SCOPED TO THE METERS, DELIBERATELY, and this is the half worth arguing about. The three tuya
 * nodes on the Energy tab are fed today by nothing but `Discovery back-off` and `Stale address
 * recovery` — there is no command path to disturb — and **a CT meter has no relay**. The worst a
 * bug here can do is set a wrong alarm threshold; it cannot switch load. The outlet and switch
 * tabs would mean ~20 nodes wired beside live relay control, which is a different risk and a
 * separate decision.
 *
 * WHAT IT ADDS, all on the Energy tab, all NEW — no existing node is modified:
 *
 *     [http in POST /capability/:deviceId] -> [Capability auth + write] -+-> [Capability router] -> the 3 tuya nodes
 *                                                        (reply, error) -+-> [http response]
 *
 * THE ROUTER KEYS ON THE PHYSICAL DEVICE, NOT THE LOGICAL ONE. `mtr_co_yellow` and
 * `mtr_lo_yellow` are two channels of ONE meter and share a single tuya node; they differ only
 * in which dp carries the setting — `warn_power1` is dp 111, `warn_power2` is dp 121. Resolving
 * that from the catalogue before routing is what stops a write landing on the neighbouring
 * branch circuit, which is the same hazard `capabilityForDevice` exists for.
 *
 * Everything the generated node needs is baked in at plan time from
 * `shared/deviceCapabilities.mjs`, because a Node-RED function node has no imports — the same
 * constraint `dpParserPlan` and `energyDayBase` work under.
 */

import { CAPABILITY_PROFILES, writableCapabilities, divisorFor } from '../shared/deviceCapabilities.mjs';
import { findParserNodes } from './dpParserPlan.mjs';

/** Marks every node this planner owns, so a re-run can tell its own work from anything else. */
export const CAPABILITY_ROUTE_MARKER = 'GENERATED by node-red-bridge/capabilityRoutePlan.mjs';

/** Fixed ids, so applying twice replaces rather than duplicates. */
export const NODE_IDS = Object.freeze({
  httpIn: 'bems_cap_in',
  auth: 'bems_cap_auth',
  router: 'bems_cap_router',
  response: 'bems_cap_res',
});

/**
 * Which devices this route may reach.
 *
 * Meters only — see the header. Named by CLASS rather than by id so a site with different
 * hardware needs no edit here, and so it can never silently acquire a device with a relay.
 */
export const ROUTED_CLASS = 'meter';

/**
 * device id -> what a write to it needs: which physical tuya node, and per capability the dp,
 * the divisor and the bounds the catalogue declares.
 *
 * `route` is the PHYSICAL device key. Two logical meters share one when they are two channels of
 * the same hardware, which is exactly the case that must not be got wrong.
 */
export function capabilityTargets(flows, registry) {
  const targets = {};
  const warnings = [];
  for (const device of registry.filter((d) => d.class === ROUTED_CLASS)) {
    const profile = CAPABILITY_PROFILES[device.capability_profile];
    if (!profile) { warnings.push(`${device.id}: no capability profile — skipped`); continue; }
    const channel = device.channel ?? 1;

    // THE DEVICE'S NODE IS DERIVED FROM THE FLOW'S OWN WIRING, never from its name. The live
    // flow calls one meter's node "AREC ACU" while the registry calls that device "CARE ACU", so
    // matching on names would have silently mis-targeted it — and writing to the wrong meter is
    // the failure this whole file is arranged to prevent.
    //
    // The structural link is unambiguous: `findParserNodes` locates a device's parser by the
    // context key it writes, and exactly one tuya node feeds that parser. Two logical meters
    // legitimately resolve to the SAME node when they are two channels of one instrument — the
    // live C.O yellow node feeds both the C.O Yellow and L.O Yellow parsers — which is why they
    // are distinguished by dp rather than by node.
    const parserIds = new Set(findParserNodes(flows, device).map((n) => n.id));
    const feeding = flows.filter((n) => n?.type === 'tuya-smart-device'
      && (n.wires ?? []).some((w) => w.some((t) => parserIds.has(t))));
    if (!parserIds.size) { warnings.push(`${device.id}: no parser node on the flow — skipped`); continue; }
    if (feeding.length !== 1) {
      warnings.push(`${device.id}: ${feeding.length} tuya nodes feed its parser, expected exactly 1 — skipped`);
      continue;
    }
    const node = feeding[0];

    const caps = {};
    for (const cap of writableCapabilities(device.capability_profile)) {
      if (cap.channel != null && cap.channel !== channel) continue;
      // KEYED BY BOTH THE BASE AND THE CHANNEL CODE, because callers legitimately use either and
      // getting it wrong is a silent 400 on a real write. `server/proxy.mjs` resolves a request
      // to this device's own code — `warn_power1` — before dispatching, while the frontend and
      // the catalogue talk in bases. Accepting one and not the other would have made every real
      // capability write fail with "not writable", which is exactly what the proxy integration
      // test caught.
      const entry = {
        code: cap.code,
        dp: cap.dp,
        divisor: divisorFor(cap),
        kind: cap.kind,
        ...(cap.min !== undefined ? { min: cap.min } : {}),
        ...(cap.max !== undefined ? { max: cap.max } : {}),
        ...(cap.range ? { range: cap.range } : {}),
      };
      caps[cap.code] = entry;
      if (cap.base && cap.base !== cap.code) caps[cap.base] = entry;
    }
    if (!Object.keys(caps).length) { warnings.push(`${device.id}: nothing writable — skipped`); continue; }

    targets[device.id] = { route: node.id, caps };
  }
  return { targets, warnings };
}

/** The auth-and-format function's source, with the target table baked in. */
export function authSrc(targets) {
  return `// ${CAPABILITY_ROUTE_MARKER}
// Do not hand-edit. Regenerate with \`npm run capability-route:pi\`.
//
// Validates a capability write and turns it into the one message shape a tuya node takes:
// { dps, set }. Everything below is resolved from shared/deviceCapabilities.mjs at plan time,
// because a function node has no imports.
const TARGETS = ${JSON.stringify(targets, null, 0)};

const TOKEN = env.get('LIGHT_API_TOKEN');
if (!TOKEN || msg.req.headers['x-auth-token'] !== TOKEN) {
    msg.statusCode = 401;
    msg.payload = { ok: false, error: 'unauthorized' };
    return [null, null, msg];
}

const target = TARGETS[msg.req.params.deviceId];
if (!target) {
    // A device with no local capability route is a 404, not a 400: the caller asked for
    // something this endpoint does not serve, and server/dispatchLight.mjs falls back to the
    // vendor cloud on a failure here rather than giving up.
    msg.statusCode = 404;
    msg.payload = { ok: false, error: 'no local capability route for this device' };
    return [null, null, msg];
}

const body = msg.payload || {};
const cap = target.caps[body.capability];
if (!cap) {
    msg.statusCode = 400;
    msg.payload = { ok: false, error: 'capability is not writable on this device' };
    return [null, null, msg];
}

let value = body.value;
if (cap.kind === 'bool') {
    if (typeof value !== 'boolean') { msg.statusCode = 400; msg.payload = { ok: false, error: 'expected a boolean' }; return [null, null, msg]; }
} else if (cap.kind === 'enum') {
    if (!cap.range || cap.range.indexOf(value) < 0) { msg.statusCode = 400; msg.payload = { ok: false, error: 'value is not in the declared range' }; return [null, null, msg]; }
} else {
    if (typeof value !== 'number' || !isFinite(value)) { msg.statusCode = 400; msg.payload = { ok: false, error: 'expected a finite number' }; return [null, null, msg]; }
    // The vendor's own bounds, never a second set written here. Refusing out of range locally
    // is what keeps a slider from asking the hardware for something it will reject silently.
    if (cap.min !== undefined && value < cap.min) { msg.statusCode = 400; msg.payload = { ok: false, error: 'below the declared minimum' }; return [null, null, msg]; }
    if (cap.max !== undefined && value > cap.max) { msg.statusCode = 400; msg.payload = { ok: false, error: 'above the declared maximum' }; return [null, null, msg]; }
    // Canonical units in, raw wire units out — the divisor is the capability's own scale.
    value = Math.round(value * cap.divisor);
}

// A FRESH MESSAGE FOR THE DEVICE, carrying nothing but what it needs.
//
// Forwarding \`msg\` itself does not work, and the failure is silent from the caller's side: an
// http-in message holds \`req\` and \`res\`, which are circular, and the tuya node serialises what
// it is given. Measured on the live meter 2026-09-08 — the endpoint answered HTTP 200 while the
// node logged \`Converting circular structure to JSON\` and the register never moved. The reply
// keeps \`res\`; the device branch keeps neither.
//
// \`topic\` is the PHYSICAL device, which is not the logical one: two channels of one meter share
// a node and differ only in dp. Routing on this is what keeps a write off the neighbouring
// branch circuit.
const accepted = { device: msg.req.params.deviceId, capability: body.capability, dp: cap.dp };
msg.statusCode = 200;
msg.payload = { ok: true, accepted: accepted };
return [{ topic: target.route, payload: { dps: cap.dp, set: value } }, msg, null];`;
}

/**
 * The nodes to add, and where they wire.
 *
 * Returns `null` when there is nothing to route — a site whose meters declare nothing writable
 * gets no endpoint rather than one that always 404s.
 */
export function planCapabilityRoute(flows, { registry, tabId }) {
  const { targets, warnings } = capabilityTargets(flows, registry);
  const routes = [...new Set(Object.values(targets).map((t) => t.route))].sort();
  if (!routes.length) return { nodes: [], targets, routes, warnings, tabId };

  const common = { z: tabId, info: CAPABILITY_ROUTE_MARKER };
  const nodes = [
    {
      ...common, id: NODE_IDS.httpIn, type: 'http in', name: 'Capability write in',
      url: '/capability/:deviceId', method: 'post', upload: false, swaggerDoc: '',
      x: 150, y: 640, wires: [[NODE_IDS.auth]],
    },
    {
      ...common, id: NODE_IDS.auth, type: 'function', name: 'Capability auth + write',
      // Three outputs: the device, the success reply, the error reply. The device branch must
      // NOT carry the http-in message — see the source's own note on circular structures.
      func: authSrc(targets), outputs: 3, noerr: 0, initialize: '', finalize: '', libs: [],
      x: 400, y: 640, wires: [[NODE_IDS.router], [NODE_IDS.response], [NODE_IDS.response]],
    },
    {
      ...common, id: NODE_IDS.router, type: 'switch', name: 'Capability router',
      property: 'topic', propertyType: 'msg', outputs: routes.length, checkall: 'false', repair: false,
      rules: routes.map((r) => ({ t: 'eq', v: r, vt: 'str' })),
      x: 660, y: 620, wires: routes.map((r) => [r]),
    },
    {
      ...common, id: NODE_IDS.response, type: 'http response', name: 'Capability reply',
      statusCode: '', headers: {}, x: 900, y: 700, wires: [],
    },
  ];
  return { nodes, targets, routes, warnings, tabId };
}

/** Replaces any previous generation of these nodes, then appends this one. */
export function applyCapabilityRoute(flows, plan) {
  const mine = new Set(Object.values(NODE_IDS));
  return [...flows.filter((n) => !mine.has(n?.id)), ...plan.nodes];
}

/**
 * Refuses anything but the addition of this planner's own nodes.
 *
 * THE INVARIANT THAT MATTERS: every pre-existing node is byte-identical afterwards. The new
 * router names three tuya nodes in its `wires`, but it does not touch them — a node's inputs are
 * not part of it. So "nothing existing changed" is checkable exactly, and this route cannot
 * reroute, disconnect or alter a single thing the building already depends on.
 */
export function validateCapabilityRoute(before, after, plan) {
  const problems = [];
  const mine = new Set(Object.values(NODE_IDS));
  const beforeById = new Map(before.filter((n) => n?.id).map((n) => [n.id, n]));
  const afterById = new Map(after.filter((n) => n?.id).map((n) => [n.id, n]));

  for (const [id, node] of beforeById) {
    if (mine.has(id)) continue;
    const now = afterById.get(id);
    if (!now) { problems.push(`node ${id} was removed`); continue; }
    if (JSON.stringify(now) !== JSON.stringify(node)) problems.push(`node ${id} was modified`);
  }
  for (const [id] of afterById) {
    if (!beforeById.has(id) && !mine.has(id)) problems.push(`unplanned node ${id} was added`);
  }
  for (const node of plan.nodes) {
    if (!afterById.has(node.id)) problems.push(`planned node ${node.id} is missing`);
    if (node.z !== plan.tabId) problems.push(`planned node ${node.id} is on the wrong tab`);
  }
  // Every routing target must be a tuya node that already existed. A typo here would wire the
  // endpoint to nothing, or to something that is not a device.
  for (const route of plan.routes) {
    const target = beforeById.get(route);
    if (!target) problems.push(`route target ${route} does not exist`);
    else if (target.type !== 'tuya-smart-device') problems.push(`route target ${route} is a ${target.type}, not a device`);
  }
  return problems;
}
