/**
 * A demultiplexer for a dual-channel meter that trades its own channels — inserted between the
 * tuya node and the two generated parsers, as a pure function over the flow array.
 *
 * WHY HERE AND NOT IN THE PARSERS OR THE BRIDGE. The parsers are generated from the catalogue and
 * verified byte-for-byte by `fix-dp-parsers:pi`; changing their template to reach across channels
 * would put the decision in two places that could drift. The bridge tab is downstream of the legacy
 * two-second integrator (`<ctx>_energy`), the day baseline and the week/month accumulator, so a
 * correction made there would leave every one of those reading the wrong clamp. One node on the
 * wire, renumbering dps before anything reads them, corrects every consumer at once and leaves
 * the parsers exactly as generated.
 *
 * WHAT THE NODE DOES. It keeps the raw dps it has seen (`<ctx1>_raw_dp`, never renumbered), asks
 * `shared/channelDemux.mjs` whether the device is currently reporting the clamps under the
 * channels the registry declares, and when it is not, moves each channel's dps to the other
 * channel's numbers before passing the message on. Status strings and anything without dps pass
 * through untouched. It records its decision under `<ctx>_channel_map` for BOTH logical devices, so
 * the bridge collector can carry it into `/api/readings/latest` and every stored row says how it was
 * attributed.
 *
 * The classifier is inlined verbatim from `shared/channelDemux.mjs` — exactly as `build-flow.mjs`
 * inlines `buildLatest.mjs` — so the scrub and the live node run the identical decision.
 *
 * ONLY ADDS ONE NODE AND MOVES ONE WIRE. `validateChannelDemux` asserts that every other node is
 * byte-identical and that the tuya node's status output still reaches the parsers directly: the
 * tab carries live control logic, and an accidental rewire there would be far harder to notice
 * than a missing node.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { CAPABILITY_PROFILES } from '../shared/deviceCapabilities.mjs';
import { findParserNodes } from './dpParserPlan.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));

export const DEMUX_NODE_ID_PREFIX = 'bems_chan_demux_';
export const GENERATED_MARKER = 'GENERATED by node-red-bridge/channelDemuxPlan.mjs';

/** The classifier as the node runs it: the module source with its `export`s stripped, LF-normalised. */
const CLASSIFIER_SRC = readFileSync(join(HERE, '..', 'shared', 'channelDemux.mjs'), 'utf8')
  .replace(/\r\n/g, '\n')
  .replace(/^export /gm, '');

/** The catalogue fields the node needs, and no others — it has no imports. */
function profileLiteral(profile) {
  return {
    id: profile.id,
    capabilities: profile.capabilities.map((c) => ({ code: c.code, dp: c.dp, base: c.base, channel: c.channel, scale: c.scale ?? 0 })),
  };
}

/**
 * @param {{ pair: {devices: string[], ceiling_w: number, never_idle: string},
 *           devices: [object, object], profile: object }} args — channel 1 device first.
 */
export function demuxNodeSrc({ pair, devices, profile }) {
  const [d1, d2] = devices;
  const keyRaw = `${d1.ctx}_raw_dp`;
  const keyMaps = [`${d1.ctx}_channel_map`, `${d2.ctx}_channel_map`];
  return `// ${GENERATED_MARKER}.
// Do not hand-edit. The rules are declared in the site file (SITE.channel_demux) and the
// classifier is shared/channelDemux.mjs, inlined below. Re-run \`npm run demux:pi\` to regenerate.
//
// Device: ${d1.id} (channel 1) / ${d2.id} (channel 2) · profile ${profile.id}
// Rules: any channel above ${pair.ceiling_w} W is ${pair.never_idle === d1.id ? d1.id : d2.id}; a channel at monitor / 0 A is the other.

${CLASSIFIER_SRC.trim()}

const PROFILE = ${JSON.stringify(profileLiteral(profile))};
const SWAP_MAP = dpSwapMapFor(PROFILE);
const RULES = { ceiling_w: ${JSON.stringify(pair.ceiling_w)} };
const K_RAW = ${JSON.stringify(keyRaw)};
const K_MAPS = ${JSON.stringify(keyMaps)};

let p = msg.payload;
let holder = null, dps = null;
if (p && typeof p === 'object') {
  if (p.data && p.data.dps && typeof p.data.dps === 'object') { holder = p.data; dps = p.data.dps; }
  else if (p.dps && typeof p.dps === 'object') { holder = p; dps = p.dps; }
}
// Status strings, GET replies without dps, anything else: not ours to touch.
if (!dps) return msg;

// Raw, as the device sent them, merged across partial reports so a message carrying one channel
// is judged against what the other last said. Never renumbered.
const raw = Object.assign({}, flow.get(K_RAW) || {}, dps);
flow.set(K_RAW, raw);

const prev = flow.get(K_MAPS[0]) || null;
const chans = readChannels(raw, PROFILE);
const next = nextChannelState(prev, { ts: Date.now(), ch1: chans.ch1, ch2: chans.ch2 }, RULES);
const flips = (prev && prev.flips ? prev.flips : 0) + (prev && prev.assignment !== next.assignment ? 1 : 0);
const map = Object.assign({}, next, { flips });
for (const k of K_MAPS) flow.set(k, map);

if (map.assignment === 'swapped') holder.dps = renumberDps(dps, SWAP_MAP);
return msg;
`;
}

/** The tuya node whose data output fans out to every id in `targets` (or to the demux already). */
function sessionFeeding(flows, targets, demuxId) {
  return flows.find((n) => {
    if (n?.type !== 'tuya-smart-device') return false;
    const data = new Set((n.wires?.[0] ?? []).flat());
    return targets.every((t) => data.has(t)) || data.has(demuxId);
  });
}

/**
 * The plan for every pair the site declares. Nothing is mutated; `unchanged: true` with a
 * `reason` is how a pair that cannot be patched safely is reported rather than half-done.
 */
export function planChannelDemux(flows, { site, registry, profiles = CAPABILITY_PROFILES }) {
  let out = flows;
  const added = [];
  const upgraded = [];
  const rewired = [];
  const reasons = [];

  for (const pair of site.channel_demux ?? []) {
    const devices = pair.devices.map((id) => registry.find((d) => d.id === id));
    if (devices.some((d) => !d)) { reasons.push(`${pair.devices.join('/')}: not in the registry`); continue; }
    const profile = profiles[devices[0].capability_profile];
    if (!profile) { reasons.push(`${pair.devices.join('/')}: no capability profile`); continue; }

    const parsers = devices.map((d) => findParserNodes(out, d));
    if (parsers.some((p) => p.length !== 1)) {
      reasons.push(`${pair.devices.join('/')}: expected exactly one parser each, found ${parsers.map((p) => p.length).join('/')}`);
      continue;
    }
    const [pA, pB] = parsers.map((p) => p[0]);
    const demuxId = `${DEMUX_NODE_ID_PREFIX}${devices[0].ctx}`;
    const tuya = sessionFeeding(out, [pA.id, pB.id], demuxId);
    if (!tuya) {
      reasons.push(`${pair.devices.join('/')}: no single tuya session feeds both parsers — collapse the sessions first (EX-037b)`);
      continue;
    }

    const src = demuxNodeSrc({ pair, devices, profile });
    const existing = out.find((n) => n.id === demuxId);
    if (existing) {
      if (existing.func === src) continue;
      out = out.map((n) => (n.id === demuxId ? { ...n, func: src } : n));
      upgraded.push(demuxId);
      continue;
    }

    const node = {
      id: demuxId,
      type: 'function',
      z: tuya.z,
      name: `Channel demux: ${devices[0].display_name} / ${devices[1].display_name}`,
      func: src,
      outputs: 1,
      noerr: 0,
      initialize: '',
      finalize: '',
      libs: [],
      // Between the session and its parsers in the editor, below the wire they used to share.
      x: (tuya.x ?? 0) + 200,
      y: (tuya.y ?? 0) + 80,
      wires: [[pA.id, pB.id]],
    };
    out = out.map((n) => (n.id === tuya.id ? { ...n, wires: [[demuxId], ...(n.wires ?? []).slice(1)] } : n));
    out = [...out, node];
    added.push(demuxId);
    rewired.push(tuya.id);
  }

  const unchanged = added.length === 0 && upgraded.length === 0;
  return {
    flows: out,
    added,
    upgraded,
    rewired,
    unchanged,
    reason: unchanged ? (reasons.join('; ') || 'demux already present and current') : reasons.join('; ') || null,
  };
}

/**
 * The refusal check. An install adds exactly the planned nodes and changes only the planned tuya
 * nodes' data output; an upgrade adds nothing and changes only the planned demux nodes' code.
 * Anything else — and any dangling wire — is a reason to write nothing.
 */
export function validateChannelDemux(before, after, plan) {
  const problems = [];
  const added = new Set(plan.added ?? []);
  const upgraded = new Set(plan.upgraded ?? []);
  const rewired = new Set(plan.rewired ?? []);

  if (after.length - before.length !== added.size) problems.push(`expected ${added.size} new node(s), got ${after.length - before.length}`);

  const beforeById = new Map(before.map((n) => [n.id, n]));
  for (const n of after) {
    const original = beforeById.get(n.id);
    if (original === undefined) {
      if (!added.has(n.id)) problems.push(`unplanned new node ${n.id}`);
      continue;
    }
    if (JSON.stringify(original) === JSON.stringify(n)) continue;
    if (upgraded.has(n.id) && JSON.stringify({ ...original, func: null }) === JSON.stringify({ ...n, func: null })) continue;
    if (rewired.has(n.id)) {
      const sameButData = JSON.stringify({ ...original, wires: null }) === JSON.stringify({ ...n, wires: null });
      const statusKept = JSON.stringify((original.wires ?? []).slice(1)) === JSON.stringify((n.wires ?? []).slice(1));
      if (sameButData && statusKept) continue;
      if (!statusKept) problems.push(`tuya node ${original.deviceName ?? n.id}: status output rewired`);
      if (!sameButData) problems.push(`tuya node ${original.deviceName ?? n.id}: changed something other than its data wire`);
      continue;
    }
    problems.push(`existing node ${original.name ?? original.deviceName ?? n.id} was modified`);
  }
  for (const id of beforeById.keys()) {
    if (!after.some((n) => n.id === id)) problems.push(`node ${id} would be removed`);
  }

  const ids = new Set(after.map((n) => n.id));
  for (const n of after) {
    for (const t of (n.wires ?? []).flat()) {
      if (!ids.has(t)) problems.push(`${n.name ?? n.deviceName ?? n.id} wires to non-existent ${t}`);
    }
  }

  // Every parser the demux feeds must still be reached from its session, through the demux.
  for (const id of [...added, ...upgraded]) {
    const demux = after.find((n) => n.id === id);
    if (!demux) { problems.push(`demux ${id} missing after apply`); continue; }
    const feeder = after.find((n) => n.type === 'tuya-smart-device' && (n.wires?.[0] ?? []).includes(id));
    if (!feeder) problems.push(`demux ${id} is not fed by any tuya session`);
    if ((demux.wires?.[0] ?? []).length !== 2) problems.push(`demux ${id} must feed exactly two parsers`);
  }
  return problems;
}
