/**
 * Generates the Node-RED source-tab parsers from the capability catalogue, as a pure function
 * over the flow array.
 *
 * WHY THIS EXISTS. Every dp this system reads is decoded by a hand-written function node on one
 * of the four source tabs — and `build-flow.mjs` deliberately does not generate those tabs. That
 * is the same exposure shape `CLAUDE.md` records for `findTimeout` and `tuyaVersion`: nothing in
 * the repository declares them, so a restored `flows.json`, a rebuilt Pi or an edit in the
 * Node-RED editor changes what the building measures with no diff and no alarm.
 *
 * It is not a hypothetical. Two faults were sitting in those nodes when this was written:
 *
 *   1. The outlet parsers read `dps["17"] / 100`. `add_ele` is scale **3**, and it reports energy
 *      *since the last report*, not a running total — so each report threw away the accumulated
 *      figure and replaced it with one small delta. `co3` drew 74.8 W all day and reported
 *      0.08 kWh. That number reached Supabase and the monthly reports.
 *   2. Nothing reset an outlet's energy at midnight. `Zero Out Energy Memory` clears the four
 *      CT meters and no outlet, so `co<n>_energy` was a lifetime counter being served as
 *      "today".
 *
 * Neither was visible in a diff, because there was nothing to diff against. Generating these
 * nodes is what makes the next one visible.
 *
 * WHAT IT PRESERVES. Every flow-context key these parsers already write, they keep writing with
 * the same meaning — the legacy `/ui` dashboard, `Calculate 3-Phase Totals` and the bridge's own
 * collectors all read them, and none of those are in this repository either. The only NEW key is
 * `<ctx>_dp`, which carries every decoded capability by code.
 *
 * Pure: takes a flow array, returns a plan. It never writes. `fix-dp-parsers.mjs` applies it,
 * dry-run by default, the same way `outletPollPlan` / `healthWiringPlan` are applied.
 */

import { CAPABILITY_PROFILES, divisorFor } from '../shared/deviceCapabilities.mjs';

/** Marks generated source so a human editing it in the Node-RED editor is warned first. */
export const GENERATED_MARKER = 'GENERATED by node-red-bridge/dpParserPlan.mjs';

/** Only these classes have a source-tab parser keyed on `<ctx>_health`. */
const PARSED_CLASSES = new Set(['outlet_dual', 'meter']);

/**
 * The compact decode table inlined into each parser: dp -> [code, divisor, kind, aliases].
 *
 * Emitted as a literal rather than shipping the catalogue into the flow, because a function node
 * cannot import anything — the same constraint that forces `buildLatest.mjs` to be inlined
 * verbatim.
 */
export function capsTableFor(profile, channel) {
  const table = {};
  for (const c of profile.capabilities) {
    // A logical device reads its OWN channel plus the device-wide dps. Taking the other
    // channel's would make one branch circuit report its neighbour's load.
    if (c.channel != null && c.channel !== channel) continue;
    const entry = [c.code, divisorFor(c), c.kind];
    if (c.kind === 'enum' && c.aliases) entry.push(c.aliases);
    table[c.dp] = entry;
  }
  return table;
}

/** `code` for this device's channel, e.g. `cur_power` -> `cur_power2`. */
function codeOf(profile, channel, base) {
  const hit = profile.capabilities.find((c) => c.base === base && (c.channel == null || c.channel === channel));
  return hit?.code ?? null;
}

const jsonLiteral = (value) => JSON.stringify(value);

/** The head every parser shares: payload unwrap, health, and the generated decode. */
function parserHead(device, profile) {
  const ctx = device.ctx;
  const channel = device.channel ?? 1;
  return `// ${GENERATED_MARKER}.
// Do not hand-edit. The dp numbers, scales, units and enum spellings below are decided in
// shared/deviceCapabilities.mjs and checked against the vendor's live device model by
// \`npm run tuya:spec\`. Editing here puts this node back outside anything that can verify it.
//
// Device: ${device.id} (${device.display_name}) · profile ${profile.id} · channel ${channel}

let p = msg.payload;
let dps = null;
if (p && typeof p === 'object') {
    if (p.data && p.data.dps) dps = p.data.dps;
    else if (p.dps) dps = p.dps;
}

// The tuya node reports CONNECTED / DISCONNECTED / ERROR on its status output; dps arriving at
// all proves the session is alive. Both shapes appear, bare and wrapped in \`.state\`.
let isOnline = flow.get("${ctx}_health") || false;
if (p === "CONNECTED" || (p.state && p.state === "CONNECTED")) isOnline = true;
else if (p === "DISCONNECTED" || p === "ERROR" || (p.state && (p.state === "DISCONNECTED" || p.state === "ERROR"))) isOnline = false;
else if (dps) isOnline = true;
flow.set("${ctx}_health", isOnline);

// dp -> [code, divisor, kind, aliases?]. \`divisor\` folds Tuya's \`scale\` and its declared unit
// into one number, so a value comes out in volts, amps, watts or kWh whatever the device chose
// to report it in — the outlet sends current as mA at scale 0, the meter as A at scale 3.
const CAPS = ${jsonLiteral(capsTableFor(profile, channel))};

let fresh = {};
if (dps) {
    for (const k in CAPS) {
        const raw = dps[k];
        if (raw === undefined || raw === null) continue;
        const c = CAPS[k];
        if (c[2] === "value") {
            const n = Number(raw);
            if (!isFinite(n)) continue;
            fresh[c[0]] = Math.round((n / c[1]) * 1e6) / 1e6;
        } else if (c[2] === "bool") {
            fresh[c[0]] = Boolean(raw);
        } else if (c[3] && c[3][raw] !== undefined) {
            fresh[c[0]] = c[3][raw];
        } else {
            fresh[c[0]] = raw;
        }
    }
}

// Last known value per capability. A setting the device only reports when it changes would
// otherwise vanish from the card on the next telemetry-only packet.
let decoded = Object.assign(flow.get("${ctx}_dp") || {}, fresh);
flow.set("${ctx}_dp", decoded);
`;
}

/**
 * The outlet tail. This is where both energy faults are fixed, and where the existing keys keep
 * their old meaning.
 */
function outletTail(device, profile) {
  const ctx = device.ctx;
  const addEle = codeOf(profile, 1, 'add_ele');
  return `
let lastV = parseFloat(flow.get("${ctx}_last_v")) || 0;
let lastC = parseFloat(flow.get("${ctx}_last_c")) || 0;
let lastP = parseFloat(flow.get("${ctx}_last_p")) || 0;
let energy = parseFloat(flow.get("${ctx}_energy")) || 0.0;
let lastTime = flow.get("${ctx}_last_time") || Date.now();
let now = Date.now();

if (fresh.cur_voltage !== undefined) lastV = fresh.cur_voltage;
if (fresh.cur_current !== undefined) lastC = fresh.cur_current;
if (fresh.cur_power !== undefined) lastP = fresh.cur_power;

// MIDNIGHT RESET. \`Zero Out Energy Memory\` clears the four CT meters and no outlet, so this
// counter used to run for the life of the flow while being served as "today". The Pi runs on
// site local time, so the local date is the right rollover.
let lastDay = flow.get("${ctx}_last_day");
let today = new Date(now).getDate();
if (lastDay === undefined || lastDay === null) flow.set("${ctx}_last_day", today);
else if (lastDay !== today) {
    energy = 0.0;
    flow.set("${ctx}_last_day", today);
}

if (dps) {
    if (fresh.${addEle} !== undefined) {
        // \`${addEle}\` is energy SINCE THE LAST REPORT, so it accumulates. Assigning it — which
        // is what this node used to do, at the wrong scale as well — discarded the day's total
        // on every packet and left a busy outlet reporting hundredths of a kWh.
        energy += fresh.${addEle};
    } else if (fresh.cur_power !== undefined) {
        // No energy dp in this packet: integrate, exactly as before. This is the weaker source
        // and it is deliberately the fallback, not the default.
        let hours = (now - lastTime) / 3600000;
        energy += (lastP / 1000) * hours;
    }
}

flow.set("${ctx}_last_time", now);
flow.set("${ctx}_last_v", lastV);
flow.set("${ctx}_last_c", lastC);
flow.set("${ctx}_last_p", lastP);
flow.set("${ctx}_energy", energy);

let timestamp = new Date().toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' });
let uiData = { name: ${jsonLiteral(device.display_name)}, titleColor: "#00b0ff", voltage: lastV.toFixed(1), current: lastC.toFixed(3), power: lastP.toFixed(1), energy: energy.toFixed(3), status: isOnline ? "CONNECTED" : "DISCONNECTED", statusColor: isOnline ? "#00e676" : "#ff1744", time: timestamp };

return [ { payload: uiData }, { payload: lastP } ];
`;
}

/**
 * The meter tail.
 *
 * `<ctx>_energy` is deliberately LEFT ALONE: it is written by the legacy two-second engine
 * (`Calculate 3-Phase Totals`) that the `/ui` dashboard reads, and rewriting a node this file
 * does not own would be a much larger change than this one. The device's own
 * `today_acc_energy` reaches the iBEMS read path through `<ctx>_dp` instead, where
 * `buildLatest` prefers it — so the accurate number is used without disturbing the legacy path.
 */
function meterTail(device, profile) {
  const ctx = device.ctx;
  const channel = device.channel ?? 1;
  const vCode = codeOf(profile, channel, 'cur_voltage');
  const cCode = codeOf(profile, channel, 'cur_current');
  const pCode = codeOf(profile, channel, 'cur_power');
  return `
let lastV = parseFloat(flow.get("${ctx}_last_v")) || 0;
let lastC = parseFloat(flow.get("${ctx}_last_c")) || 0;
let lastP = parseFloat(flow.get("${ctx}_last_p")) || 0;

// Channel ${channel} of this product: dps ${
    [vCode, cCode, pCode].map((code) => profile.capabilities.find((c) => c.code === code)?.dp).join(', ')
  }.
if (fresh.${vCode} !== undefined) lastV = fresh.${vCode};
if (fresh.${cCode} !== undefined) lastC = fresh.${cCode};
if (fresh.${pCode} !== undefined) lastP = fresh.${pCode};

flow.set("${ctx}_last_v", lastV);
flow.set("${ctx}_last_c", lastC);
flow.set("${ctx}_last_p", lastP);
flow.set("${ctx}_last_time", Date.now());

// Written by the legacy two-second engine, not here. The device's own today_acc_energy travels
// to the bridge on \`${ctx}_dp\` instead of overwriting this.
let energy = parseFloat(flow.get("${ctx}_energy")) || 0.0;

let arrV = flow.get("${ctx}_arr_v") || []; let arrC = flow.get("${ctx}_arr_c") || []; let arrP = flow.get("${ctx}_arr_p") || [];
arrV.push(lastV); flow.set("${ctx}_arr_v", arrV);
arrC.push(lastC); flow.set("${ctx}_arr_c", arrC);
arrP.push(lastP); flow.set("${ctx}_arr_p", arrP);

let timestamp = new Date().toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' });
let uiData = { name: ${jsonLiteral(`${device.display_name} Module`)}, titleColor: "#ffd700", voltage: lastV.toFixed(1), current: lastC.toFixed(3), power: lastP.toFixed(1), energy: energy.toFixed(3), status: isOnline ? "CONNECTED" : "DISCONNECTED", statusColor: isOnline ? "#00e676" : "#ff1744", time: timestamp };

return [ { payload: uiData }, { payload: lastP } ];
`;
}

/** The full generated source for one device's parser. */
export function generateParserSource(device, profile) {
  const tail = device.class === 'outlet_dual' ? outletTail(device, profile) : meterTail(device, profile);
  return parserHead(device, profile) + tail;
}

/**
 * The Switch tab's collector, which is a different shape from the metered parsers: one node
 * serves all seven lights, keyed by `msg.lightId`, and it writes into GLOBAL context
 * (`lightStatus`) rather than flow context because the Lighting Logic Hub and the bridge's own
 * switch collector both read it from elsewhere.
 *
 * The three fields it already maintains — `conn`, `on`, `lastSeen` — keep their exact meaning;
 * `buildLatest` derives every switch's `online` from `conn` and would report the whole lighting
 * circuit offline if this drifted. What is added is `dp`, so a light switch can surface its
 * countdown, power-on behaviour and inching setting like every other device.
 */
export function generateSwitchCollectorSource(profile) {
  return `// ${GENERATED_MARKER}.
// Do not hand-edit — see shared/deviceCapabilities.mjs (profile ${profile.id}).
//
// One node for all seven lights, keyed by msg.lightId. Writes global.lightStatus, which the
// Lighting Logic Hub and the bridge's switch collector both read.

const id = msg.lightId;
const m = global.get('lightStatus') || {};
const cur = m[id] || { id: id, conn: 'unknown', on: null, lastSeen: null };
const p = msg.payload || {};
if (p.state) { cur.conn = String(p.state).toUpperCase(); cur.lastSeen = new Date().toISOString(); }

let dps = null;
if (p.data && p.data.dps) dps = p.data.dps;
else if (p.dps) dps = p.dps;

const CAPS = ${jsonLiteral(capsTableFor(profile, 1))};

if (dps) {
    const decoded = cur.dp || {};
    for (const k in CAPS) {
        const raw = dps[k];
        if (raw === undefined || raw === null) continue;
        const c = CAPS[k];
        if (c[2] === "value") {
            const n = Number(raw);
            if (!isFinite(n)) continue;
            decoded[c[0]] = Math.round((n / c[1]) * 1e6) / 1e6;
        } else if (c[2] === "bool") {
            decoded[c[0]] = Boolean(raw);
        } else if (c[3] && c[3][raw] !== undefined) {
            decoded[c[0]] = c[3][raw];
        } else {
            decoded[c[0]] = raw;
        }
    }
    cur.dp = decoded;
}

// Unchanged: the relay's own state, and the fact that hearing anything proves the link is up.
if (dps && dps['1'] !== undefined) {
    cur.on = Boolean(dps['1']);
    cur.conn = 'CONNECTED';
    cur.lastSeen = new Date().toISOString();
}

m[id] = cur;
global.set('lightStatus', m);
return null;`;
}

/**
 * Which node parses a given device.
 *
 * Matched on the `<ctx>_health` write it performs, not on its name, because the name is a label
 * somebody can change and the context key is the contract. `AREC ACU` has TWO nodes writing
 * `arec_health` — the Energy tab's `Unified Parser` and the Aircon tab's `Daily Parser` — so the
 * name is used to disambiguate, and any other writer is reported rather than quietly rewritten.
 */
export function findParserNodes(flows, device) {
  const needle = `flow.set("${device.ctx}_health"`;
  return flows.filter((n) => n?.type === 'function' && typeof n.func === 'string' && n.func.includes(needle));
}

/**
 * The plan: what would change, what would not, and what could not be resolved.
 *
 * Nothing is mutated. `changes` is empty when the flow already matches, which is what makes
 * re-running safe and what lets the runner say "nothing to do" honestly.
 */
export function planDpParsers(flows, { registry, profiles = CAPABILITY_PROFILES } = {}) {
  const changes = [];
  const warnings = [];
  const skipped = [];

  for (const device of registry) {
    if (!PARSED_CLASSES.has(device.class)) continue;
    if (!device.ctx) {
      warnings.push({ device: device.id, reason: 'no flow-context prefix; cannot locate a parser' });
      continue;
    }
    const profile = profiles[device.capability_profile];
    if (!profile) {
      warnings.push({ device: device.id, reason: `no capability profile (${device.capability_profile ?? 'null'})` });
      continue;
    }

    const matches = findParserNodes(flows, device);
    const unified = matches.filter((n) => /Unified Parser/i.test(n.name ?? ''));
    const others = matches.filter((n) => !/Unified Parser/i.test(n.name ?? ''));

    for (const other of others) {
      // Deliberately not rewritten: the Aircon tab's `AREC ACU Daily Parser` also writes
      // `arec_health`, and it belongs to a different tab with a different job. Saying so is the
      // point — silently leaving it would be the same class of undeclared state this file exists
      // to remove.
      warnings.push({
        device: device.id,
        node: other.id,
        name: other.name,
        reason: 'also writes this health key but is not a Unified Parser — left untouched, review by hand',
      });
    }

    if (unified.length === 0) {
      warnings.push({ device: device.id, reason: `no "Unified Parser" node writes ${device.ctx}_health` });
      continue;
    }
    if (unified.length > 1) {
      warnings.push({ device: device.id, reason: `${unified.length} Unified Parser nodes write ${device.ctx}_health; refusing to guess` });
      continue;
    }

    const node = unified[0];
    const after = generateParserSource(device, profile);
    if (node.func === after) {
      skipped.push({ device: device.id, node: node.id, name: node.name });
      continue;
    }
    changes.push({
      device: device.id,
      node: node.id,
      name: node.name,
      tab: node.z,
      before: node.func,
      after,
      wasGenerated: typeof node.func === 'string' && node.func.includes(GENERATED_MARKER),
    });
  }

  // The lights' collector: one node, all seven switches, a different shape from the metered
  // parsers. Located by the global key it writes, because that is the contract — the node's
  // name is a label somebody can change.
  const switchProfile = profiles.tdq_switch;
  const lightDevices = registry.filter((d) => d.class === 'switch');
  if (switchProfile && lightDevices.length) {
    const collectors = flows.filter(
      (n) => n?.type === 'function' && typeof n.func === 'string' && n.func.includes("global.set('lightStatus'"),
    );
    if (collectors.length === 0) {
      warnings.push({ device: '(lights)', reason: "no function node writes global.lightStatus" });
    } else if (collectors.length > 1) {
      warnings.push({ device: '(lights)', reason: `${collectors.length} nodes write global.lightStatus; refusing to guess` });
    } else {
      const node = collectors[0];
      const after = generateSwitchCollectorSource(switchProfile);
      if (node.func === after) {
        skipped.push({ device: '(lights)', node: node.id, name: node.name });
      } else {
        changes.push({
          device: '(lights)',
          node: node.id,
          name: node.name,
          tab: node.z,
          before: node.func,
          after,
          wasGenerated: node.func.includes(GENERATED_MARKER),
        });
      }
    }
  }

  return { changes, warnings, skipped };
}

/** Apply a plan to a COPY of the flow array. The original is never touched. */
export function applyDpParserPlan(flows, plan) {
  const byId = new Map(plan.changes.map((c) => [c.node, c.after]));
  return flows.map((n) => (byId.has(n?.id) ? { ...n, func: byId.get(n.id) } : n));
}

/**
 * The refusal check. Run against the before and after flows, it must come back empty or nothing
 * is written.
 *
 * The context-key invariant is the important one. These parsers write keys that the legacy `/ui`
 * dashboard, the two-second totals engine and the bridge collectors all read, and **none of
 * those readers are in this repository**. A generated parser that quietly stopped writing one
 * would break a dashboard nobody would think to open, on a change whose diff looked fine.
 */
export function validateDpParserPlan(before, after, plan) {
  const problems = [];

  if (before.length !== after.length) {
    problems.push(`node count changed: ${before.length} -> ${after.length}`);
    return problems;
  }

  const planned = new Map(plan.changes.map((c) => [c.node, c]));
  for (let i = 0; i < before.length; i += 1) {
    const a = before[i];
    const b = after[i];
    if (a?.id !== b?.id) {
      problems.push(`node ${i} changed identity: ${a?.id} -> ${b?.id}`);
      continue;
    }
    if (!planned.has(a?.id)) {
      if (JSON.stringify(a) !== JSON.stringify(b)) problems.push(`unplanned change to node ${a?.id} (${a?.name ?? ''})`);
      continue;
    }
    // A planned node may differ in `func` and in nothing else.
    const strippedA = { ...a, func: null };
    const strippedB = { ...b, func: null };
    if (JSON.stringify(strippedA) !== JSON.stringify(strippedB)) {
      problems.push(`node ${a.id} (${a.name}) changed something other than its code`);
    }
    const lost = [...keysWrittenBy(a.func)].filter((k) => !keysWrittenBy(b.func).has(k));
    if (lost.length) {
      problems.push(`node ${a.id} (${a.name}) would stop writing: ${lost.join(', ')}`);
    }
  }
  return problems;
}

/** Every `flow.set("key"` a parser performs — the contract with readers outside this repo. */
export function keysWrittenBy(source) {
  return new Set([...String(source ?? '').matchAll(/flow\.set\("([^"]+)"/g)].map((m) => m[1]));
}
