/**
 * Generates the Node-RED nodes a newly enrolled device needs, as a pure function.
 *
 * A device is only real once BOTH halves exist: a registry entry (so every service knows it)
 * and flow nodes (so something actually polls it). This module is the second half.
 *
 * WHAT IT GENERATES, and why that is all of it:
 *   - a `tuya-smart-device` node, carrying the settings `shared/tuyaNodeSettings.mjs` records
 *     as correct rather than the library defaults that cost this project four days;
 *   - a parser function writing the `<ctx>_*` flow-context keys that `buildLatest` reads.
 *
 * It does NOT touch the bridge tab. That tab is generated from the registry by
 * `build-flow.mjs`, so once the registry entry exists the collector picks the device up on the
 * next `npm run build:flow && npm run deploy:pi`. Duplicating that logic here would create a
 * second implementation of the same mapping, and the two would drift.
 *
 * The parser is a template rather than bespoke code because every existing one is the same
 * shape modulo two things: the context prefix and the DPS numbers. Generating it means a new
 * device cannot get a subtly different parser from its neighbours — which is how `co_yel` and
 * `lo_yel2` ended up with slightly different online-detection in the first place.
 */

import { DPS_MAPS } from '../shared/registry.mjs';
import { TUYA_FIND_TIMEOUT } from '../shared/tuyaNodeSettings.mjs';

/**
 * Reads the same shape every existing Unified Parser has. Written as a template string rather
 * than assembled from fragments so that what lands in the flow is readable by whoever opens
 * Node-RED next — a generated node nobody can read is a node nobody will maintain.
 */
function parserSource(ctx, dpsMap) {
  const m = DPS_MAPS[dpsMap];
  const readings = [
    `    if (dps["${m.v}"] !== undefined) lastV = dps["${m.v}"] / ${m.scale.v};`,
    `    if (dps["${m.c}"] !== undefined) lastC = dps["${m.c}"] / ${m.scale.c};`,
    `    if (dps["${m.p}"] !== undefined) lastP = dps["${m.p}"] / ${m.scale.p};`,
  ];
  if (m.energy !== undefined) {
    readings.push(`    if (dps["${m.energy}"] !== undefined) energy = dps["${m.energy}"] / ${m.scale.energy};`);
  }
  return `// Generated by node-red-bridge/enrollPlan.mjs. Same shape as every other Unified
// Parser: identify the payload, decide health, then read this device's own DPS numbers.
let p = msg.payload;
let dps = null;
if (p && typeof p === 'object') {
    if (p.data && p.data.dps) dps = p.data.dps;
    else if (p.dps) dps = p.dps;
}

// Health. A status string moves it; receiving any dps proves the socket is alive.
let isOnline = flow.get("${ctx}_health") || false;
if (p === "CONNECTED" || (p.state && p.state === "CONNECTED")) isOnline = true;
else if (p === "DISCONNECTED" || p === "ERROR" || (p.state && (p.state === "DISCONNECTED" || p.state === "ERROR"))) isOnline = false;
else if (dps) isOnline = true;
flow.set("${ctx}_health", isOnline);

// Readings. Each is carried forward when absent rather than zeroed: a dps that did not
// arrive is "unchanged", and zeroing it would report a real 0 W the device never sent.
let lastV = parseFloat(flow.get("${ctx}_last_v")) || 0;
let lastC = parseFloat(flow.get("${ctx}_last_c")) || 0;
let lastP = parseFloat(flow.get("${ctx}_last_p")) || 0;
let energy = parseFloat(flow.get("${ctx}_energy")) || 0.0;

if (dps) {
${readings.join('\n')}
    // Only stamped when dps actually arrived. Stamping on a status event would make a
    // reconnected-but-silent device look freshly measured — see ROADMAP EX-033b.
    flow.set("${ctx}_last_time", Date.now());
}

flow.set("${ctx}_last_v", lastV);
flow.set("${ctx}_last_c", lastC);
flow.set("${ctx}_last_p", lastP);
flow.set("${ctx}_energy", energy);

return null;`;
}

/**
 * @param entry        a registry entry from `registryEntryFor`
 * @param credentials  { tuyaDeviceId, localKey, tuyaVersion }
 * @param placement    { z, x, y } — the tab and canvas position
 */
export function planEnrollment(flows, entry, credentials, placement) {
  const problems = [];
  if (!entry?.ctx) problems.push(`${entry?.id ?? 'device'} has no ctx — only metered classes can be generated this way`);
  if (!credentials?.tuyaDeviceId) problems.push('vendor device id missing');
  if (!credentials?.localKey) problems.push('local key missing');
  if (!credentials?.tuyaVersion) problems.push('protocol version missing — match what the device announces, never a default');
  if (flows.some((n) => n?.type === 'tuya-smart-device' && n.deviceId === credentials?.tuyaDeviceId)) {
    problems.push('that vendor device already has a node in this flow');
  }
  const deviceNodeId = `bems_enrolled_${entry?.id}`;
  const parserNodeId = `bems_enrolled_${entry?.id}_parser`;
  if (flows.some((n) => n.id === deviceNodeId || n.id === parserNodeId)) {
    problems.push(`${entry.id} is already enrolled in this flow`);
  }
  if (problems.length) return { flows, added: [], problems };

  const parser = {
    id: parserNodeId,
    type: 'function',
    z: placement.z,
    name: `${entry.display_name} Unified Parser`,
    func: parserSource(entry.ctx, entry.dps_map),
    outputs: 1,
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: placement.x + 260,
    y: placement.y,
    wires: [[]],
  };
  const device = {
    id: deviceNodeId,
    type: 'tuya-smart-device',
    z: placement.z,
    deviceName: entry.display_name,
    deviceId: credentials.tuyaDeviceId,
    deviceKey: credentials.localKey,
    deviceIp: '',
    disableAutoStart: false,
    storeAsCreds: false,
    // Not the library defaults. `findTimeout` at 1000ms caught one broadcast in five, and a
    // wrong version fails as `find() timed out` — both cost days. See shared/tuyaNodeSettings.
    findTimeout: TUYA_FIND_TIMEOUT,
    retryTimeout: '1000',
    tuyaVersion: credentials.tuyaVersion,
    eventMode: 'event-both',
    logLevel: 'log-level-error',
    x: placement.x,
    y: placement.y,
    wires: [[parserNodeId]],
  };

  return { flows: [...flows, device, parser], added: [device, parser], problems: [] };
}

/** Invariants. Additive only — nothing existing may change. */
export function validateEnrollmentPlan(before, after) {
  const problems = [];
  if (after.length !== before.length + 2) problems.push(`expected 2 new nodes, got ${after.length - before.length}`);
  const beforeById = new Map(before.map((n) => [n.id, JSON.stringify(n)]));
  for (const n of after) {
    const was = beforeById.get(n.id);
    if (was !== undefined && was !== JSON.stringify(n)) problems.push(`existing node ${n.name ?? n.id} was modified`);
  }
  for (const id of beforeById.keys()) if (!after.some((n) => n.id === id)) problems.push(`node ${id} would be removed`);
  const ids = new Set(after.map((n) => n.id));
  for (const n of after) {
    for (const t of (n.wires ?? []).flat()) if (!ids.has(t)) problems.push(`${n.name ?? n.id} wires to non-existent ${t}`);
  }
  // Every device node must reach a parser, or it polls hardware nobody reads.
  for (const n of after.filter((x) => x.type === 'tuya-smart-device')) {
    if (!(n.wires ?? []).flat().length) problems.push(`${n.deviceName} has no parser`);
  }
  return problems;
}
